window.HYPE_MOVIES={
  "provider": "Watchmode",
  "image_provider": "TMDB",
  "generated_at": "2026-10-10T15:57:26.570Z",
  "refresh_hours": 24,
  "estimated_credits_this_refresh": 56,
  "tmdb_requests_this_refresh": 48,
  "popular": [
    {
      "id": 1939424,
      "title": "Resident Evil",
      "year": 2026,
      "release_date": "2026-09-16",
      "genres": [
        "Horror",
        "Science Fiction",
        "Adventure"
      ],
      "runtime_minutes": 95,
      "user_rating": 7.8,
      "critic_score": 88,
      "us_rating": null,
      "plot": "A medical courier finds himself fighting to survive when a horrifying night suddenly descends into chaos. Cut off from safety, he must navigate escalating danger and uncertainty while trying to make it through until morning.",
      "trailer": "https://www.youtube.com/watch?v=mNd1gb19A-c",
      "imdb_id": "tt35538033",
      "tmdb_id": 1423191,
      "watchmode_url": "https://www.watchmode.com/title/1939424/",
      "poster_path": "/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg",
      "backdrop_path": "/3icyRAqgakNcQn6aDVz9libFmBA.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/3icyRAqgakNcQn6aDVz9libFmBA.jpg"
    },
    {
      "id": 1869118,
      "title": "The Odyssey",
      "year": 2026,
      "release_date": "2026-07-15",
      "genres": [
        "Adventure",
        "Action",
        "Fantasy"
      ],
      "runtime_minutes": 173,
      "user_rating": 8.6,
      "critic_score": 91,
      "us_rating": "R",
      "plot": "After a devastating war, a legendary king begins a long, perilous journey home. Along the way, he faces powerful gods, terrifying monsters, dangerous temptations, and difficult choices that test his cleverness, courage, and humanity, while his family struggles with his prolonged absence and uncertainty about his return.",
      "trailer": "https://www.youtube.com/watch?v=Mzw2ttJD2qQ",
      "imdb_id": "tt33764258",
      "tmdb_id": 1368337,
      "watchmode_url": "https://www.watchmode.com/title/1869118/",
      "poster_path": "/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg",
      "backdrop_path": "/bulFtfy3oBQtCnAMSi7g6DSSds3.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/bulFtfy3oBQtCnAMSi7g6DSSds3.jpg"
    },
    {
      "id": 1773876,
      "title": "Spider-Man: Brand New Day",
      "year": 2026,
      "release_date": "2026-07-29",
      "genres": [
        "Science Fiction",
        "Action",
        "Adventure"
      ],
      "runtime_minutes": 145,
      "user_rating": 8.2,
      "critic_score": 78,
      "us_rating": "PG-13",
      "plot": "A full-time crimefighter protects a city that has forgotten who he is, while watching people from his past move on without him. As loneliness and strange changes in his abilities add to the pressure, he must face a dangerous new threat that puts the city and those he cares about at risk.",
      "trailer": "https://www.youtube.com/watch?v=62bIsvRcPv0",
      "imdb_id": "tt22084616",
      "tmdb_id": 969681,
      "watchmode_url": "https://www.watchmode.com/title/1773876/",
      "poster_path": "/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg",
      "backdrop_path": "/4tjxYg2AbOzzG9G1YuiT2NzYhlH.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/4tjxYg2AbOzzG9G1YuiT2NzYhlH.jpg"
    },
    {
      "id": 1823717,
      "title": "Insidious: Out of the Further",
      "year": 2026,
      "release_date": "2026-08-19",
      "genres": [
        "Horror",
        "Thriller"
      ],
      "runtime_minutes": 106,
      "user_rating": 6.3,
      "critic_score": 52,
      "us_rating": null,
      "plot": "A young mother raising her daughter in the house where she grew up discovers she can enter a parallel realm inhabited by dangerous spirits. When she learns she can bring entities from that world into reality, she must confront a growing supernatural threat while protecting her family.",
      "trailer": "https://www.youtube.com/watch?v=jxU8FU3o75A",
      "imdb_id": "tt32393988",
      "tmdb_id": 1291595,
      "watchmode_url": "https://www.watchmode.com/title/1823717/",
      "poster_path": "/4tTrW9dXCByS5wt2pXVWb58zNjz.jpg",
      "backdrop_path": "/p40lmrdI4blcAPZQMTPaiy5v5Ym.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/4tTrW9dXCByS5wt2pXVWb58zNjz.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/p40lmrdI4blcAPZQMTPaiy5v5Ym.jpg"
    },
    {
      "id": 191063,
      "title": "Loves of a French Pussycat",
      "year": 1972,
      "release_date": "1972-03-09",
      "genres": [
        "Comedy"
      ],
      "runtime_minutes": 94,
      "user_rating": 4.5,
      "critic_score": null,
      "us_rating": "R",
      "plot": "Rolf, a sex-advice columnist and a lecher, has affairs with numerous women, but never a permanent relationship. Suzanne, one of his ex-lovers, offers to bet that no woman can get Rolf to propose marriage, a bet her girlfriend Andrea eagerly accepts. But there's a catch: To win the bet, Andrea must get the womanizing Rolf to commit to marriage without first going to bed with him.",
      "trailer": null,
      "imdb_id": "tt0068986",
      "tmdb_id": 264980,
      "watchmode_url": "https://www.watchmode.com/title/191063/",
      "poster_path": "/1WGq9cMuj09tnTJ5wdkINOJff04.jpg",
      "backdrop_path": "/wVg11RahrRfghgqViuoJgcJL1iM.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/1WGq9cMuj09tnTJ5wdkINOJff04.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/wVg11RahrRfghgqViuoJgcJL1iM.jpg"
    },
    {
      "id": 1624092,
      "title": "Coyote vs. Acme",
      "year": 2026,
      "release_date": "2026-08-17",
      "genres": [
        "Comedy",
        "Adventure",
        "Family"
      ],
      "runtime_minutes": 103,
      "user_rating": 7.6,
      "critic_score": 87,
      "us_rating": "PG",
      "plot": "After another Acme product backfires during his pursuit of the Roadrunner, a determined coyote takes the corporation to court with help from a struggling billboard lawyer. Their case brings cartoon chaos, courtroom clashes, and a fresh challenge for the company behind his long-running disasters.",
      "trailer": "https://www.youtube.com/watch?v=H-43VeYGiPM",
      "imdb_id": "tt1756855",
      "tmdb_id": 1204680,
      "watchmode_url": "https://www.watchmode.com/title/1624092/",
      "poster_path": "/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg",
      "backdrop_path": "/viZqGq9TNvQ5uXSD4ahg2RpRONT.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/viZqGq9TNvQ5uXSD4ahg2RpRONT.jpg"
    },
    {
      "id": 1882453,
      "title": "The End of Oak Street",
      "year": 2026,
      "release_date": "2026-08-12",
      "genres": [
        "Science Fiction",
        "Mystery",
        "Thriller"
      ],
      "runtime_minutes": 100,
      "user_rating": 6.4,
      "critic_score": 78,
      "us_rating": "PG-13",
      "plot": "After a mysterious cosmic event tears an ordinary suburban neighborhood from its surroundings, a family finds itself in an unknown, prehistoric wilderness. With familiar streets transformed and danger closing in, they must work together to survive, protect one another, and find a way forward.",
      "trailer": "https://www.youtube.com/watch?v=3oB9AxspVow",
      "imdb_id": "tt27165187",
      "tmdb_id": 1101383,
      "watchmode_url": "https://www.watchmode.com/title/1882453/",
      "poster_path": "/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg",
      "backdrop_path": "/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg"
    },
    {
      "id": 1875027,
      "title": "Runner",
      "year": 2026,
      "release_date": "2026-09-07",
      "genres": [
        "Action",
        "Comedy"
      ],
      "runtime_minutes": 97,
      "user_rating": 6.5,
      "critic_score": 66,
      "us_rating": "PG-13",
      "plot": "A former soldier and an unlikely partner race across dangerous territory to complete a critical medical delivery. Hunted by a ruthless cartel, they must stay ahead of their pursuers while trying to save a little girl’s life.",
      "trailer": "https://www.youtube.com/watch?v=m8JUmBgHejI",
      "imdb_id": "tt31349844",
      "tmdb_id": 1377237,
      "watchmode_url": "https://www.watchmode.com/title/1875027/",
      "poster_path": "/yBKMAIj7clP42UkFejhGDBBoTpb.jpg",
      "backdrop_path": "/iXR79oKsLHwLno9jdzxxeFP21sy.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/yBKMAIj7clP42UkFejhGDBBoTpb.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/iXR79oKsLHwLno9jdzxxeFP21sy.jpg"
    },
    {
      "id": 1821586,
      "title": "Mutiny",
      "year": 2026,
      "release_date": "2026-08-19",
      "genres": [
        "Action",
        "Thriller"
      ],
      "runtime_minutes": 96,
      "user_rating": 5.9,
      "critic_score": 51,
      "us_rating": "R",
      "plot": "After witnessing his employer’s murder and being framed for the crime, a disgraced former policeman hides aboard a cargo ship to pursue revenge. As he navigates the vessel and faces a heavily armed crew, he uncovers a wider international conspiracy tied to the killing.",
      "trailer": "https://www.youtube.com/watch?v=FKSdXH89jbo",
      "imdb_id": "tt32338669",
      "tmdb_id": 1288445,
      "watchmode_url": "https://www.watchmode.com/title/1821586/",
      "poster_path": "/pu2VxGlpGwffOx292w18b1tv96j.jpg",
      "backdrop_path": "/e2QAGrEmbpmZpMymDRkDisJkvg9.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/pu2VxGlpGwffOx292w18b1tv96j.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/e2QAGrEmbpmZpMymDRkDisJkvg9.jpg"
    },
    {
      "id": 1942846,
      "title": "Fall 2: Deadpoint",
      "year": 2026,
      "release_date": "2026-09-01",
      "genres": [
        "Thriller"
      ],
      "runtime_minutes": 98,
      "user_rating": 5.7,
      "critic_score": 58,
      "us_rating": "PG-13",
      "plot": "Two climbers travel to Thailand to attempt a forbidden route across Mount Kwan, hoping to confront their fears. Thousands of feet above the ground, unstable paths, extreme exposure, and limited options turn the dangerous journey into a desperate fight to survive.",
      "trailer": "https://www.youtube.com/watch?v=Krs0VDIjhmE",
      "imdb_id": "tt31192372",
      "tmdb_id": 1101412,
      "watchmode_url": "https://www.watchmode.com/title/1942846/",
      "poster_path": "/fgSm5ylwiXbIHn8UbUXDjk9RRu4.jpg",
      "backdrop_path": "/yBDxqDB29kpH9VojTytjGWBgmdJ.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/fgSm5ylwiXbIHn8UbUXDjk9RRu4.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/yBDxqDB29kpH9VojTytjGWBgmdJ.jpg"
    },
    {
      "id": 1779945,
      "title": "The Fix",
      "year": 2026,
      "release_date": "2026-09-10",
      "genres": [
        "Action",
        "Thriller"
      ],
      "runtime_minutes": 142,
      "user_rating": 4.9,
      "critic_score": null,
      "us_rating": "R",
      "plot": "Disillusioned by the end of the war in Afghanistan, a group of disgraced, war-torn former CIA operatives sets out for Tehran to pursue a life-changing score, confronting the consequences of their past while risking everything on an ambitious mission.",
      "trailer": "https://www.youtube.com/watch?v=NYC0v8xqQdM",
      "imdb_id": "tt9601292",
      "tmdb_id": 1228834,
      "watchmode_url": "https://www.watchmode.com/title/1779945/",
      "poster_path": "/yopXjun3ICFfJci2ukcEzceZjUs.jpg",
      "backdrop_path": "/yT8EkAvEkJDFeAxK7s7HlIPELRT.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/yopXjun3ICFfJci2ukcEzceZjUs.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/yT8EkAvEkJDFeAxK7s7HlIPELRT.jpg"
    },
    {
      "id": 11229413,
      "title": "After Impact",
      "year": 2026,
      "release_date": "2026-09-15",
      "genres": [
        "Science Fiction",
        "Drama",
        "Thriller"
      ],
      "runtime_minutes": 95,
      "user_rating": 3.1,
      "critic_score": null,
      "us_rating": "NR",
      "plot": "After losing a parent, a man inherits a vast greenhouse as an asteroid threatens Earth. As society breaks down, he retreats to a family bunker and struggles with injury, isolation, betrayal, and the difficult choices survival demands when a faint radio signal suggests someone else may still be out there.",
      "trailer": "https://www.youtube.com/watch?v=Af8D6sRDyxo",
      "imdb_id": "tt36809539",
      "tmdb_id": 1751701,
      "watchmode_url": "https://www.watchmode.com/title/11229413/",
      "poster_path": "/yzDuAQCY2n6zzOlBkn6JzhLhY3k.jpg",
      "backdrop_path": "/k22XyPbce7zvzzf5OnT4uaY8ZD1.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/yzDuAQCY2n6zzOlBkn6JzhLhY3k.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/k22XyPbce7zvzzf5OnT4uaY8ZD1.jpg"
    },
    {
      "id": 1793884,
      "title": "Digger",
      "year": 2026,
      "release_date": "2026-09-28",
      "genres": [
        "Comedy",
        "Drama"
      ],
      "runtime_minutes": 129,
      "user_rating": 7.5,
      "critic_score": 49,
      "us_rating": "R",
      "plot": "A powerful oil tycoon faces a frantic crisis after a disaster linked to his company threatens to unleash catastrophe. As he works with political leaders and scientists to respond, he must confront the consequences of his actions and the forces shaping the unfolding emergency.",
      "trailer": "https://www.youtube.com/watch?v=qORTe1wW3Wg",
      "imdb_id": "tt31450459",
      "tmdb_id": 1248832,
      "watchmode_url": "https://www.watchmode.com/title/1793884/",
      "poster_path": "/1ATXKrIPJyKNwnJ6lcG088Sa6zi.jpg",
      "backdrop_path": "/u3EtxdmZeiliW98c5Oegk5LIGZa.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/1ATXKrIPJyKNwnJ6lcG088Sa6zi.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/u3EtxdmZeiliW98c5Oegk5LIGZa.jpg"
    },
    {
      "id": 11042837,
      "title": "The Love Hypothesis",
      "year": 2026,
      "release_date": "2026-09-23",
      "genres": [
        "Romance",
        "Comedy"
      ],
      "runtime_minutes": 112,
      "user_rating": 7.1,
      "critic_score": 67,
      "us_rating": "R",
      "plot": "A biology PhD candidate and a demanding professor enter a fake relationship to solve their romantic dilemmas. What begins as a carefully planned arrangement soon complicates their views on love, forcing both to navigate unexpected feelings and the pressures of academic life.",
      "trailer": "https://www.youtube.com/watch?v=xwdamnfS6IM",
      "imdb_id": "tt22526100",
      "tmdb_id": 1032863,
      "watchmode_url": "https://www.watchmode.com/title/11042837/",
      "poster_path": "/vfZxVHextAGC70zrNhS8lsROqP1.jpg",
      "backdrop_path": "/o7Oy9Gbx1CCyaweL8xUhtMW4Puq.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/vfZxVHextAGC70zrNhS8lsROqP1.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/o7Oy9Gbx1CCyaweL8xUhtMW4Puq.jpg"
    },
    {
      "id": 1855581,
      "title": "Obsession",
      "year": 2026,
      "release_date": "2026-05-13",
      "genres": [
        "Horror",
        "Thriller"
      ],
      "runtime_minutes": 109,
      "user_rating": 8,
      "critic_score": 85,
      "us_rating": null,
      "plot": "After using a mysterious wish-granting object to win over his longtime crush, a hopeful romantic gets exactly what he wanted. But the altered relationship quickly turns unsettling, forcing him to confront the frightening consequences of trying to control another person’s feelings.",
      "trailer": "https://www.youtube.com/watch?v=0G5CjgPw1x4",
      "imdb_id": "tt37287335",
      "tmdb_id": 1339713,
      "watchmode_url": "https://www.watchmode.com/title/1855581/",
      "poster_path": "/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg",
      "backdrop_path": "/5lTZyuBTNOfawsfPT8Q0cIg6qAF.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/5lTZyuBTNOfawsfPT8Q0cIg6qAF.jpg"
    },
    {
      "id": 1823785,
      "title": "Toy Story 5",
      "year": 2026,
      "release_date": "2026-06-17",
      "genres": [
        "Animation",
        "Family",
        "Comedy",
        "Adventure"
      ],
      "runtime_minutes": 102,
      "user_rating": 7.5,
      "critic_score": 83,
      "us_rating": null,
      "plot": "When a child becomes absorbed in a new tablet, her beloved toys face an unexpected challenge to playtime. As the group struggles to stay connected with her, they must adapt to changing interests and work together to protect their place in her world.",
      "trailer": "https://www.youtube.com/watch?v=c51ND9Hdbw0",
      "imdb_id": "tt29355505",
      "tmdb_id": 1084244,
      "watchmode_url": "https://www.watchmode.com/title/1823785/",
      "poster_path": "/sfQtVlIHljToOwYjhe21KPGzZWK.jpg",
      "backdrop_path": "/qjTqY5coNiz6sVtPng40IzltsoN.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/sfQtVlIHljToOwYjhe21KPGzZWK.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/qjTqY5coNiz6sVtPng40IzltsoN.jpg"
    },
    {
      "id": 1784996,
      "title": "Animals",
      "year": 2026,
      "release_date": "2026-10-09",
      "genres": [
        "Thriller",
        "Drama"
      ],
      "runtime_minutes": 106,
      "user_rating": 2.1,
      "critic_score": null,
      "us_rating": "R",
      "plot": "After the son of a mayoral candidate is kidnapped, the candidate and his wife have only a few hours to find the ransom. With most of their money tied up in the campaign, they must take desperate steps that bring hidden parts of their lives into view.",
      "trailer": "https://www.youtube.com/watch?v=mlBfQJ8oxB0",
      "imdb_id": "tt31049299",
      "tmdb_id": 1236045,
      "watchmode_url": "https://www.watchmode.com/title/1784996/",
      "poster_path": "/cyltXU1lAGhRFBuHQIMWBAPj8fI.jpg",
      "backdrop_path": "/tzoarEu7TsG959upiELyYPm5kO9.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/cyltXU1lAGhRFBuHQIMWBAPj8fI.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/tzoarEu7TsG959upiELyYPm5kO9.jpg"
    },
    {
      "id": 1513886,
      "title": "Resident Evil: Welcome to Raccoon City",
      "year": 2021,
      "release_date": "2021-11-24",
      "genres": [
        "Action",
        "Horror",
        "Science Fiction"
      ],
      "runtime_minutes": 107,
      "user_rating": 5.4,
      "critic_score": 37,
      "us_rating": "R",
      "plot": "In a declining Midwestern town once dominated by a pharmaceutical company, a hidden evil is unleashed beneath the surface. As residents change and danger spreads, a small group of survivors must work together to uncover the truth and survive the night.",
      "trailer": "https://www.youtube.com/watch?v=4q6UGCyHZCI",
      "imdb_id": "tt6920084",
      "tmdb_id": 460458,
      "watchmode_url": "https://www.watchmode.com/title/1513886/",
      "poster_path": "/bArhvjRHl535XMaSh9VjInF2mSZ.jpg",
      "backdrop_path": "/wYtEvBmpBRXPdwGgr1gcWiwJSI7.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/bArhvjRHl535XMaSh9VjInF2mSZ.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/wYtEvBmpBRXPdwGgr1gcWiwJSI7.jpg"
    },
    {
      "id": 1782549,
      "title": "Pinocchio: Unstrung",
      "year": 2026,
      "release_date": "2026-07-22",
      "genres": [
        "Horror",
        "Fantasy",
        "Mystery"
      ],
      "runtime_minutes": 82,
      "user_rating": 5.6,
      "critic_score": 55,
      "us_rating": "NR",
      "plot": "Created by a toymaker and influenced by a sinister cricket, a wooden boy begins a violent quest to become human. As he pursues this goal piece by piece, the dark bond shaping his journey turns a familiar fairy tale into a grim horror story.",
      "trailer": "https://www.youtube.com/watch?v=Y4lZewE6JMI",
      "imdb_id": "tt30887701",
      "tmdb_id": 1232569,
      "watchmode_url": "https://www.watchmode.com/title/1782549/",
      "poster_path": "/eUJXk3bTvLBi5Zcb0BCedZU7lVL.jpg",
      "backdrop_path": "/vgZDb7kmaxP24cFbt1KJdMLlHFZ.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/eUJXk3bTvLBi5Zcb0BCedZU7lVL.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/vgZDb7kmaxP24cFbt1KJdMLlHFZ.jpg"
    },
    {
      "id": 1225505,
      "title": "Siren: Erotic Ghost",
      "year": 2004,
      "release_date": "2004-10-22",
      "genres": [
        "Horror"
      ],
      "runtime_minutes": 76,
      "user_rating": 4,
      "critic_score": null,
      "us_rating": null,
      "plot": "When a crew of bank robbers believes that an alluring young woman has blown their cover, they kidnap the girl. Back at their hideout they develop sinister plans to rape and then kill her. When one of the crooks mysteriously turns up dead however, they begin to realize that their intended victim may be a powerful, vindictive, supernatural force.",
      "trailer": null,
      "imdb_id": "tt0468862",
      "tmdb_id": 52720,
      "watchmode_url": "https://www.watchmode.com/title/1225505/",
      "poster_path": "/q7CzzcTuYNQHQgoubf1FjPVo7id.jpg",
      "backdrop_path": "/sHLDucxRYKTL73tzd922Eynudxb.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/q7CzzcTuYNQHQgoubf1FjPVo7id.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/sHLDucxRYKTL73tzd922Eynudxb.jpg"
    }
  ],
  "upcoming": [
    {
      "id": 11000067,
      "title": "Always Lalisa",
      "year": 2026,
      "release_date": "2026-10-12",
      "genres": [
        "Documentary",
        "Music"
      ],
      "runtime_minutes": 98,
      "user_rating": 7.2,
      "critic_score": null,
      "us_rating": "NR",
      "plot": "Documentary following global superstar LISA during a transformative year away from BLACKPINK, the K-pop phenomenon that made her one of the world's most recognizable performers. Documenting a year of risk, reinvention, and self-discovery as LISA begins to define her next chapter.",
      "trailer": "https://www.youtube.com/watch?v=KAjC7EFzGKU",
      "imdb_id": "tt37108970",
      "tmdb_id": 1489932,
      "watchmode_url": "https://www.watchmode.com/title/11000067/",
      "poster_path": "/pOZnrUX1UMblLiqq9ZtZUde3cQV.jpg",
      "backdrop_path": "/wJwTuwy1ZajIA6ivGjoe0Ee08XN.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/pOZnrUX1UMblLiqq9ZtZUde3cQV.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/wJwTuwy1ZajIA6ivGjoe0Ee08XN.jpg"
    },
    {
      "id": 1689779,
      "title": "Minotaur",
      "year": 2026,
      "release_date": "2026-10-14",
      "genres": [
        "Crime",
        "Drama",
        "Thriller"
      ],
      "runtime_minutes": 135,
      "user_rating": 7.6,
      "critic_score": 85,
      "us_rating": null,
      "plot": "When Gleb, a successful company director, finds himself under siege from mounting corporate pressures, an increasingly unstable world, and the discovery of his wife's affair, the collapse of his carefully ordered life accelerates toward violence.",
      "trailer": "https://www.youtube.com/watch?v=hTHeFP0mcuk",
      "imdb_id": "tt37118301",
      "tmdb_id": 848700,
      "watchmode_url": "https://www.watchmode.com/title/1689779/",
      "poster_path": "/bM37B5CuMWrPyGPpNsKzTGict4Q.jpg",
      "backdrop_path": "/i5HacpkXOKQ85lfbnMO3jXvAnPy.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/bM37B5CuMWrPyGPpNsKzTGict4Q.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/i5HacpkXOKQ85lfbnMO3jXvAnPy.jpg"
    },
    {
      "id": 1950265,
      "title": "Iron Boy",
      "year": 2026,
      "release_date": "2026-10-14",
      "genres": [
        "Animation",
        "Drama",
        "Family"
      ],
      "runtime_minutes": 90,
      "user_rating": 7.6,
      "critic_score": 79,
      "us_rating": null,
      "plot": "In rural France, 10-year-old Christophe tries to live up to his rigid and distant father on the family farm. But the young boy starts to lean over and collapse without warning — on the tractor, at school, at dinner... A doctor finds the solution: Christophe must wear an iron corset to keep himself upright. Forced to reinvent his life away from the farm, Christophe discovers a new passion for music, meets a new friend, and follows her into his first mischief. But will any of this really fix what is out of balance?",
      "trailer": null,
      "imdb_id": "tt36639956",
      "tmdb_id": 947493,
      "watchmode_url": "https://www.watchmode.com/title/1950265/",
      "poster_path": "/aXNm7mgW22mxCSwSV7i7GHjy6Ga.jpg",
      "backdrop_path": "/3e0Lzs4vDSHjRULFw6vPI4jyHd6.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/aXNm7mgW22mxCSwSV7i7GHjy6Ga.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/3e0Lzs4vDSHjRULFw6vPI4jyHd6.jpg"
    },
    {
      "id": 11229535,
      "title": "You Can See Everything",
      "year": 2026,
      "release_date": "2026-10-16",
      "genres": [
        "Documentary"
      ],
      "runtime_minutes": 174,
      "user_rating": 7.6,
      "critic_score": null,
      "us_rating": null,
      "plot": "Thirty-four days before reporting to prison, a notorious Silicon Valley founder invites a skeptical film crew to document her life. The project expands into an intimate, unsettling three-year examination of ambition, public scrutiny, and the boundaries between personal portrait and spectacle.",
      "trailer": "https://www.youtube.com/watch?v=HvW_N5p1q44",
      "imdb_id": "tt45368240",
      "tmdb_id": 1765072,
      "watchmode_url": "https://www.watchmode.com/title/11229535/",
      "poster_path": "/Ap8QwmKfSjYbWC4XIP8w9pdn72O.jpg",
      "backdrop_path": "/nhIL3O4W9h5V5JbNQm7yjoDk3So.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/Ap8QwmKfSjYbWC4XIP8w9pdn72O.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/nhIL3O4W9h5V5JbNQm7yjoDk3So.jpg"
    },
    {
      "id": 1757035,
      "title": "Wicker",
      "year": 2026,
      "release_date": "2026-10-21",
      "genres": [
        "Romance",
        "Fantasy",
        "Comedy"
      ],
      "runtime_minutes": 105,
      "user_rating": 7.2,
      "critic_score": 75,
      "us_rating": null,
      "plot": "In a tight-knit fishing village, a social outcast asks a local craftsperson to create a husband from wicker. As she grows unexpectedly attached to the handmade companion, the relationship stirs gossip and jealousy, putting pressure on the community’s fragile sense of order.",
      "trailer": "https://www.youtube.com/watch?v=HP0BWBWn14I",
      "imdb_id": "tt29611136",
      "tmdb_id": 1195803,
      "watchmode_url": "https://www.watchmode.com/title/1757035/",
      "poster_path": "/eOYkNDalgt1v6UGjw3AoFR5qo9D.jpg",
      "backdrop_path": "/xVh1ypMoVkMf5IB7y3hnRplJ14c.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/eOYkNDalgt1v6UGjw3AoFR5qo9D.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/xVh1ypMoVkMf5IB7y3hnRplJ14c.jpg"
    },
    {
      "id": 1914859,
      "title": "Clayface",
      "year": 2026,
      "release_date": "2026-10-21",
      "genres": [
        "Horror",
        "Thriller",
        "Science Fiction"
      ],
      "runtime_minutes": 108,
      "user_rating": 7.9,
      "critic_score": null,
      "us_rating": "R",
      "plot": "Matt Hagen's meteoric rise from Gotham street kid to Hollywood leading man is tragically cut short when a local crime boss's actions leave him horribly disfigured. Abandoned by his team and with nothing left, Matt seeks out a cutting edge treatment that miraculously returns him to his former self… but also unexpectedly affects his grip on reality, spiraling him down a destructive path of all-consuming revenge.",
      "trailer": "https://www.youtube.com/watch?v=OGO4Mqvo3jI",
      "imdb_id": "tt34890576",
      "tmdb_id": 1400940,
      "watchmode_url": "https://www.watchmode.com/title/1914859/",
      "poster_path": "/5jCpQnWPikggmQZoDp1eAi6BI6w.jpg",
      "backdrop_path": "/1A7s8zG4PF6YoJrncrTO6N4r0Sx.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/5jCpQnWPikggmQZoDp1eAi6BI6w.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/1A7s8zG4PF6YoJrncrTO6N4r0Sx.jpg"
    },
    {
      "id": 1969393,
      "title": "Coward",
      "year": 2026,
      "release_date": "2026-10-21",
      "genres": [
        "Drama",
        "Romance",
        "War"
      ],
      "runtime_minutes": 120,
      "user_rating": 7.1,
      "critic_score": 73,
      "us_rating": null,
      "plot": "During the First World War, soldiers working behind the front line struggle to keep their spirits up. Inspired by war rhetoric, each person searches for a personal way to cope amid the pressures of conflict.",
      "trailer": "https://www.youtube.com/watch?v=vyRlBGfVlvQ",
      "imdb_id": "tt39328391",
      "tmdb_id": 1437981,
      "watchmode_url": "https://www.watchmode.com/title/1969393/",
      "poster_path": "/jhBDAdVy7qPglzcBsPDMJXQ9Cls.jpg",
      "backdrop_path": "/tW0ZxAcvLNZiSvHnBS2lpNOGB2S.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/jhBDAdVy7qPglzcBsPDMJXQ9Cls.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/tW0ZxAcvLNZiSvHnBS2lpNOGB2S.jpg"
    },
    {
      "id": 11126829,
      "title": "La Gradiva",
      "year": 2026,
      "release_date": "2026-10-21",
      "genres": [
        "Drama"
      ],
      "runtime_minutes": 145,
      "user_rating": 7.3,
      "critic_score": 95,
      "us_rating": null,
      "plot": "Amid the ancient ruins of Pompeii, a group of French teenagers on a class trip to Naples grapple with anxiety and exhilaration ahead of their high school graduation.",
      "trailer": "https://www.youtube.com/watch?v=5yY6V9MbEoE",
      "imdb_id": "tt36107185",
      "tmdb_id": 1154730,
      "watchmode_url": "https://www.watchmode.com/title/11126829/",
      "poster_path": "/y6AkOgTEPM9nTJUOeyvHqlf6Bgp.jpg",
      "backdrop_path": "/aFO0i3bl4d6o0odPix8xgiVsIYT.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/y6AkOgTEPM9nTJUOeyvHqlf6Bgp.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/aFO0i3bl4d6o0odPix8xgiVsIYT.jpg"
    },
    {
      "id": 1987809,
      "title": "The Diary of a Chambermaid",
      "year": 2026,
      "release_date": "2026-10-23",
      "genres": [
        "Drama",
        "Comedy"
      ],
      "runtime_minutes": 94,
      "user_rating": 6.7,
      "critic_score": 76,
      "us_rating": null,
      "plot": "Gianina, a young Romanian chambermaid, works for a bourgeois family in Bordeaux and spends her evenings rehearsing a maid’s story with an amateur theater group. She cares for her employer’s son while her own daughter grows up far away in Romania, and as Christmas nears, the hope of reunion grows stronger.",
      "trailer": null,
      "imdb_id": "tt38785098",
      "tmdb_id": 1472813,
      "watchmode_url": "https://www.watchmode.com/title/1987809/",
      "poster_path": "/vktQLUEEjg1KZhXfDINqxZNB29x.jpg",
      "backdrop_path": "/bYaiKiCmTOnd2EW0yuzA4vno8g.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/vktQLUEEjg1KZhXfDINqxZNB29x.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/bYaiKiCmTOnd2EW0yuzA4vno8g.jpg"
    },
    {
      "id": 1988409,
      "title": "The Only Living Pickpocket in New York",
      "year": 2026,
      "release_date": "2026-10-23",
      "genres": [
        "Crime",
        "Drama"
      ],
      "runtime_minutes": 88,
      "user_rating": 7,
      "critic_score": null,
      "us_rating": null,
      "plot": "An aging pickpocket navigates a New York where cash is fading and his skills are tested. After he takes a valuable USB stick by mistake, he must race to return it and calm a dangerous crime family—while also caring for his disabled wife.",
      "trailer": "https://www.youtube.com/watch?v=iXA7BmrBBxs",
      "imdb_id": "tt36482679",
      "tmdb_id": 1458099,
      "watchmode_url": "https://www.watchmode.com/title/1988409/",
      "poster_path": "/pNdB9va2AEPQe9UfhKAdIt8nus9.jpg",
      "backdrop_path": "/nZLt2sLZTEOyK50TjwNlGqzWsp5.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/pNdB9va2AEPQe9UfhKAdIt8nus9.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/nZLt2sLZTEOyK50TjwNlGqzWsp5.jpg"
    },
    {
      "id": 11097329,
      "title": "BTS: THE RETURN",
      "year": 2026,
      "release_date": "2026-10-25",
      "genres": [
        "Documentary",
        "Music"
      ],
      "runtime_minutes": 93,
      "user_rating": 9.3,
      "critic_score": null,
      "us_rating": null,
      "plot": "A globally celebrated music group reunites in Los Angeles to record a new album. This documentary offers rare access to their creative process, group dynamic, and fresh chapter as they work together in a new era.",
      "trailer": "https://www.youtube.com/watch?v=jRig7JvOpWg",
      "imdb_id": "tt39578551",
      "tmdb_id": 1628116,
      "watchmode_url": "https://www.watchmode.com/title/11097329/",
      "poster_path": "/9CNUWleZWN9EGMZjvaSTcxmAAGg.jpg",
      "backdrop_path": "/w4jOh7ok6JvsYu6WbuSDW97D7D6.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/9CNUWleZWN9EGMZjvaSTcxmAAGg.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/w4jOh7ok6JvsYu6WbuSDW97D7D6.jpg"
    },
    {
      "id": 1953127,
      "title": "Moulin",
      "year": 2026,
      "release_date": "2026-10-28",
      "genres": [
        "History",
        "Drama",
        "War"
      ],
      "runtime_minutes": 130,
      "user_rating": 5.9,
      "critic_score": null,
      "us_rating": null,
      "plot": "In June 1943, Jean Moulin, leader of the French Resistance, is arrested while attempting to reunite the forces of the \"Armée Secrète.\" Interrogated by Klaus Barbie, the head of the Gestapo in Lyon, Moulin is drawn into a relentless confrontation.",
      "trailer": null,
      "imdb_id": "tt36899180",
      "tmdb_id": 1437925,
      "watchmode_url": "https://www.watchmode.com/title/1953127/",
      "poster_path": "/f3yopLJXRBcPvgkfRji1jloDrxd.jpg",
      "backdrop_path": "/bcH6CmYcHuPnAQXUhW0Rr5hFuvc.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/f3yopLJXRBcPvgkfRji1jloDrxd.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/bcH6CmYcHuPnAQXUhW0Rr5hFuvc.jpg"
    },
    {
      "id": 1985219,
      "title": "Species",
      "year": 2026,
      "release_date": "2026-10-28",
      "genres": [
        "Science Fiction",
        "Horror"
      ],
      "runtime_minutes": 103,
      "user_rating": 6.4,
      "critic_score": null,
      "us_rating": null,
      "plot": "Margot, a young intern at the country's most competitive ER, struggles in the high-pressure environment. When multiple patients her age arrive with strange symptoms, her own body begins experiencing alarming transformations.",
      "trailer": "https://www.youtube.com/watch?v=56TE9NuZQhs",
      "imdb_id": "tt37799273",
      "tmdb_id": 1468846,
      "watchmode_url": "https://www.watchmode.com/title/1985219/",
      "poster_path": "/fDvZvNmLIwUcKKQ4Cfb6TmQJM7M.jpg",
      "backdrop_path": "/jySTVXi8UDajVgYh01KavKtY4YJ.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/fDvZvNmLIwUcKKQ4Cfb6TmQJM7M.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/jySTVXi8UDajVgYh01KavKtY4YJ.jpg"
    },
    {
      "id": 11021641,
      "title": "Ozzy & Black Sabbath: Back to the Beginning",
      "year": 2026,
      "release_date": "2026-10-28",
      "genres": [
        "Music",
        "Documentary"
      ],
      "runtime_minutes": 147,
      "user_rating": 8.6,
      "critic_score": null,
      "us_rating": null,
      "plot": "A landmark farewell concert reunites pioneering heavy metal performers for a high-energy celebration of classic songs. The live event also features guest artists and other bands performing tributes and original material, creating a powerful salute to the genre’s enduring legacy.",
      "trailer": null,
      "imdb_id": "tt46055956",
      "tmdb_id": 1515139,
      "watchmode_url": "https://www.watchmode.com/title/11021641/",
      "poster_path": "/iO8vwdtmOivoyUguheJtDLXp2Gq.jpg",
      "backdrop_path": "/hFIhPUW8oO2EJYXLAuWFMJBzjsR.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/iO8vwdtmOivoyUguheJtDLXp2Gq.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/hFIhPUW8oO2EJYXLAuWFMJBzjsR.jpg"
    },
    {
      "id": 1795869,
      "title": "The Blood Countess",
      "year": 2026,
      "release_date": "2026-10-29",
      "genres": [
        "Horror",
        "Comedy",
        "Fantasy",
        "Mystery"
      ],
      "runtime_minutes": 119,
      "user_rating": 5.1,
      "critic_score": null,
      "us_rating": null,
      "plot": "A powerful vampire and her maid pursue a legendary elixir and a book that could endanger their supernatural world. Chasing them are a determined police inspector, two vampire experts, an unconventional nephew, and his therapist.",
      "trailer": "https://www.youtube.com/watch?v=jNG343pAJxI",
      "imdb_id": "tt28151657",
      "tmdb_id": 1251608,
      "watchmode_url": "https://www.watchmode.com/title/1795869/",
      "poster_path": "/jKIAwCSDTv9i4J6KrAY1YpEvrGH.jpg",
      "backdrop_path": "/9IdxfMvkZzO8wjnygz784OzaK03.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/jKIAwCSDTv9i4J6KrAY1YpEvrGH.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/9IdxfMvkZzO8wjnygz784OzaK03.jpg"
    },
    {
      "id": 1942282,
      "title": "Free at Heart",
      "year": 2025,
      "release_date": "2026-10-29",
      "genres": [
        "Drama",
        "Family",
        "Romance"
      ],
      "runtime_minutes": 116,
      "user_rating": 6.8,
      "critic_score": null,
      "us_rating": null,
      "plot": "A sheltered teen’s small-town routine is shaken when his family takes in another boy his age. As the two grow closer, they uncover a complicated family connection that strains trust at home and forces them to navigate intense feelings, secrecy, and the pressure of community judgment.",
      "trailer": "https://www.youtube.com/watch?v=0tVpYYFlbJw",
      "imdb_id": "tt40204609",
      "tmdb_id": 1427540,
      "watchmode_url": "https://www.watchmode.com/title/1942282/",
      "poster_path": "/byxSlSW5KB0xkvTSBRkD4LZtxNL.jpg",
      "backdrop_path": "/2nH7Enpai65oTZoEJGQ57mWmSpg.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/byxSlSW5KB0xkvTSBRkD4LZtxNL.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/2nH7Enpai65oTZoEJGQ57mWmSpg.jpg"
    },
    {
      "id": 11026751,
      "title": "The Restoration at Grayson Manor",
      "year": 2025,
      "release_date": "2026-10-29",
      "genres": [
        "Horror"
      ],
      "runtime_minutes": 96,
      "user_rating": 5.6,
      "critic_score": null,
      "us_rating": null,
      "plot": "After an accident leaves a young man without his hands, his mother turns to radical technology in hopes of helping him recover. Their efforts unfold at the family manor, where the promise of restoration brings difficult choices and unsettling uncertainty.",
      "trailer": "https://www.youtube.com/watch?v=eb2OTdBLKUg",
      "imdb_id": "tt32767134",
      "tmdb_id": 1528009,
      "watchmode_url": "https://www.watchmode.com/title/11026751/",
      "poster_path": "/m9aKkiCwlQWri27z9WEwezfkUcw.jpg",
      "backdrop_path": "/eOassvwSzhNfHzPA00XtDD0jYs4.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/m9aKkiCwlQWri27z9WEwezfkUcw.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/eOassvwSzhNfHzPA00XtDD0jYs4.jpg"
    },
    {
      "id": 1421481,
      "title": "The Strange Little Cat",
      "year": 2013,
      "release_date": "2026-10-30",
      "genres": [
        "Comedy",
        "Drama",
        "Family"
      ],
      "runtime_minutes": 72,
      "user_rating": 6.3,
      "critic_score": 80,
      "us_rating": null,
      "plot": "It is a Saturday in autumn, and Karin and Simon are visiting their parents and youngest sister Clara. This family gathering provides the occasion for a dinner together, at which other relatives appear over the course of the day. While the family members animate the apartment’s space with their conversations, everyday activities and cooking preparations, the cat and dog range through the various rooms. they too become a central element in this quotidian familial dance that repeatedly manifests stylized elements, disrupting any naturalistic mode of presentation. In this way, adjoining spaces open up between family drama, fairy tale and the psychological study of a mother.",
      "trailer": "https://www.youtube.com/watch?v=ZSIqAjoz-p0",
      "imdb_id": "tt2586000",
      "tmdb_id": 164328,
      "watchmode_url": "https://www.watchmode.com/title/1421481/",
      "poster_path": "/bcGc12rQIoEQzxgA2x0YKwYTM5B.jpg",
      "backdrop_path": "/4j1e7Gol1rM2uscJbEcJ3kEmzJn.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/bcGc12rQIoEQzxgA2x0YKwYTM5B.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/4j1e7Gol1rM2uscJbEcJ3kEmzJn.jpg"
    },
    {
      "id": 1647844,
      "title": "Wild Horse Nine",
      "year": 2026,
      "release_date": "2026-10-30",
      "genres": [
        "Comedy",
        "Crime",
        "Thriller"
      ],
      "runtime_minutes": 116,
      "user_rating": 7.9,
      "critic_score": null,
      "us_rating": null,
      "plot": "Shortly before the 1973 Chilean coup, CIA agents Chris and Lee are dispatched from Santiago to Easter Island by their bureau chief, MJ. Amongst the Island's iconic statues, and as the longtime partners wrestle with their dark pasts and present conspiracies, Chris's newfound bond with a pair of rebellious students threatens to send everyone’s trip to this remote paradise sideways.",
      "trailer": "https://www.youtube.com/watch?v=Haw_sznA5aQ",
      "imdb_id": "tt15799564",
      "tmdb_id": 891621,
      "watchmode_url": "https://www.watchmode.com/title/1647844/",
      "poster_path": "/dNJFRtVg3xLQ7dbNIQ55cmmIniD.jpg",
      "backdrop_path": "/b17UWf3LqHgKolQkXckne32qv0.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/dNJFRtVg3xLQ7dbNIQ55cmmIniD.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/b17UWf3LqHgKolQkXckne32qv0.jpg"
    },
    {
      "id": 11074184,
      "title": "Nuisance Bear",
      "year": 2026,
      "release_date": "2026-11-01",
      "genres": [
        "Documentary"
      ],
      "runtime_minutes": 90,
      "user_rating": 7,
      "critic_score": 70,
      "us_rating": null,
      "plot": "A polar bear struggles to survive as its ancient migration brings it into contact with tourists, wildlife officers, and hunters. As people label the sacred predator a nuisance, the film explores who belongs in a landscape shared by humans and wildlife.",
      "trailer": null,
      "imdb_id": "tt39150922",
      "tmdb_id": 1595210,
      "watchmode_url": "https://www.watchmode.com/title/11074184/",
      "poster_path": "/An1QdmHWNxX2V03kq3akOCid69r.jpg",
      "backdrop_path": "/hqDiQteXWMoyezEmbPy0nRYdUST.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/An1QdmHWNxX2V03kq3akOCid69r.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/hqDiQteXWMoyezEmbPy0nRYdUST.jpg"
    }
  ],
  "kids": [
    {
      "id": 178503,
      "title": "Coco",
      "year": 2017,
      "release_date": "2017-10-27",
      "genres": [
        "Family",
        "Animation",
        "Music",
        "Adventure"
      ],
      "runtime_minutes": 105,
      "user_rating": 8.5,
      "critic_score": 89,
      "us_rating": "PG",
      "plot": "Despite a generations-old family ban on music, a young aspiring guitarist pursues his dream and is swept into the vibrant Land of the Dead. With help from a charming trickster, he races to uncover the truth about his family’s history and find a way home.",
      "trailer": "https://www.youtube.com/watch?v=Rvr68u6k5sI",
      "imdb_id": "tt2380307",
      "tmdb_id": 354912,
      "watchmode_url": "https://www.watchmode.com/title/178503/",
      "poster_path": "/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg",
      "backdrop_path": "/g7CHF8gTLGooTbP4GznIGwaqAGL.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/g7CHF8gTLGooTbP4GznIGwaqAGL.jpg"
    },
    {
      "id": 1749638,
      "title": "The Wild Robot",
      "year": 2024,
      "release_date": "2024-09-12",
      "genres": [
        "Family",
        "Animation",
        "Science Fiction",
        "Adventure"
      ],
      "runtime_minutes": 102,
      "user_rating": 8.3,
      "critic_score": 91,
      "us_rating": null,
      "plot": "After a shipwreck, an intelligent robot is stranded on an uninhabited island. As the robot learns to survive among wary animals, it forms an unexpected bond with an orphaned gosling and takes on the challenge of raising it in the wild.",
      "trailer": "https://www.youtube.com/watch?v=67vbA5ZJdKQ",
      "imdb_id": "tt29623480",
      "tmdb_id": 1184918,
      "watchmode_url": "https://www.watchmode.com/title/1749638/",
      "poster_path": "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
      "backdrop_path": "/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg"
    },
    {
      "id": 1184041,
      "title": "Inside Out",
      "year": 2015,
      "release_date": "2015-06-17",
      "genres": [
        "Animation",
        "Family",
        "Adventure",
        "Drama",
        "Comedy"
      ],
      "runtime_minutes": 95,
      "user_rating": 8.2,
      "critic_score": 96,
      "us_rating": null,
      "plot": "When an 11-year-old girl moves to a new city, her emotions struggle to guide her through the upheaval. As Joy and Sadness become separated from the others, they travel through unfamiliar parts of her mind while trying to restore balance and help her cope with change.",
      "trailer": "https://www.youtube.com/watch?v=_MC3XuMvsDI",
      "imdb_id": "tt2096673",
      "tmdb_id": 150540,
      "watchmode_url": "https://www.watchmode.com/title/1184041/",
      "poster_path": "/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
      "backdrop_path": "/jJKZaTBNenlFclQyjrnvzkRmvWE.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/jJKZaTBNenlFclQyjrnvzkRmvWE.jpg"
    },
    {
      "id": 1409773,
      "title": "The Nightmare Before Christmas",
      "year": 1993,
      "release_date": "1993-10-09",
      "genres": [
        "Fantasy",
        "Animation",
        "Family"
      ],
      "runtime_minutes": 76,
      "user_rating": 8.1,
      "critic_score": 89,
      "us_rating": "PG",
      "plot": "A weary Halloween figure discovers the wonders of Christmas and decides to bring the holiday’s cheer to a world built around scares. As the unusual plan takes shape, a thoughtful rag-doll companion worries about its consequences and tries to set things right.",
      "trailer": "https://www.youtube.com/watch?v=lVtetOjX_vk",
      "imdb_id": "tt0107688",
      "tmdb_id": 9479,
      "watchmode_url": "https://www.watchmode.com/title/1409773/",
      "poster_path": "/oQffRNjK8e19rF7xVYEN8ew0j7b.jpg",
      "backdrop_path": "/dSfrsjhqC6lYe7LYDYnzWeXZmEl.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/oQffRNjK8e19rF7xVYEN8ew0j7b.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/dSfrsjhqC6lYe7LYDYnzWeXZmEl.jpg"
    },
    {
      "id": 1982660,
      "title": "Forgotten Island",
      "year": 2026,
      "release_date": "2026-09-10",
      "genres": [
        "Animation",
        "Adventure",
        "Fantasy",
        "Comedy",
        "Family"
      ],
      "runtime_minutes": 109,
      "user_rating": 8,
      "critic_score": 84,
      "us_rating": null,
      "plot": "During their final night together, two high school graduates discover a mysterious portal leading to a fantastical island. When they learn that returning home could cost them every memory of their friendship, they race across the island to find another way back before they forget each other.",
      "trailer": "https://www.youtube.com/watch?v=a8RHqN93qfo",
      "imdb_id": "tt36583977",
      "tmdb_id": 1465063,
      "watchmode_url": "https://www.watchmode.com/title/1982660/",
      "poster_path": "/myd1K3gefdNAWFsGNRDdMeiK9Qg.jpg",
      "backdrop_path": "/cNICUho5uiAGkfCAQq1ihyaMla4.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/myd1K3gefdNAWFsGNRDdMeiK9Qg.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/cNICUho5uiAGkfCAQq1ihyaMla4.jpg"
    },
    {
      "id": 1624092,
      "title": "Coyote vs. Acme",
      "year": 2026,
      "release_date": "2026-08-17",
      "genres": [
        "Comedy",
        "Adventure",
        "Family"
      ],
      "runtime_minutes": 103,
      "user_rating": 7.6,
      "critic_score": 87,
      "us_rating": "PG",
      "plot": "After another Acme product backfires during his pursuit of the Roadrunner, a determined coyote takes the corporation to court with help from a struggling billboard lawyer. Their case brings cartoon chaos, courtroom clashes, and a fresh challenge for the company behind his long-running disasters.",
      "trailer": "https://www.youtube.com/watch?v=H-43VeYGiPM",
      "imdb_id": "tt1756855",
      "tmdb_id": 1204680,
      "watchmode_url": "https://www.watchmode.com/title/1624092/",
      "poster_path": "/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg",
      "backdrop_path": "/viZqGq9TNvQ5uXSD4ahg2RpRONT.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/viZqGq9TNvQ5uXSD4ahg2RpRONT.jpg"
    },
    {
      "id": 1823785,
      "title": "Toy Story 5",
      "year": 2026,
      "release_date": "2026-06-17",
      "genres": [
        "Animation",
        "Family",
        "Comedy",
        "Adventure"
      ],
      "runtime_minutes": 102,
      "user_rating": 7.5,
      "critic_score": 83,
      "us_rating": null,
      "plot": "When a child becomes absorbed in a new tablet, her beloved toys face an unexpected challenge to playtime. As the group struggles to stay connected with her, they must adapt to changing interests and work together to protect their place in her world.",
      "trailer": "https://www.youtube.com/watch?v=c51ND9Hdbw0",
      "imdb_id": "tt29355505",
      "tmdb_id": 1084244,
      "watchmode_url": "https://www.watchmode.com/title/1823785/",
      "poster_path": "/sfQtVlIHljToOwYjhe21KPGzZWK.jpg",
      "backdrop_path": "/qjTqY5coNiz6sVtPng40IzltsoN.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/sfQtVlIHljToOwYjhe21KPGzZWK.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/qjTqY5coNiz6sVtPng40IzltsoN.jpg"
    },
    {
      "id": 1785478,
      "title": "Zootopia 2",
      "year": 2025,
      "release_date": "2025-11-26",
      "genres": [
        "Animation",
        "Adventure",
        "Comedy",
        "Mystery",
        "Family"
      ],
      "runtime_minutes": 108,
      "user_rating": 7.5,
      "critic_score": 83,
      "us_rating": "PG",
      "plot": "After solving a major case, two police partners follow a twisting mystery when a snake’s arrival disrupts the animal metropolis. Their investigation takes them undercover into unfamiliar parts of town, testing their teamwork while raising questions about prejudice, stereotypes, greed, and the city’s past.",
      "trailer": "https://www.youtube.com/watch?v=BjkIOU5PhyQ",
      "imdb_id": "tt26443597",
      "tmdb_id": 1084242,
      "watchmode_url": "https://www.watchmode.com/title/1785478/",
      "poster_path": "/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg",
      "backdrop_path": "/lgotja3xMoJZbynwHfcQcJAEMWH.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/lgotja3xMoJZbynwHfcQcJAEMWH.jpg"
    },
    {
      "id": 1840434,
      "title": "Minions & Monsters",
      "year": 2026,
      "release_date": "2026-06-24",
      "genres": [
        "Adventure",
        "Animation",
        "Comedy",
        "Family",
        "Fantasy"
      ],
      "runtime_minutes": 90,
      "user_rating": 6.5,
      "critic_score": 80,
      "us_rating": "PG",
      "plot": "A group of chaotic yellow movie hopefuls storms Hollywood and becomes famous before a major change sends them tumbling back down. When their attempt to make a monster movie unleashes real danger, they must work together to stop the mayhem and protect the world.",
      "trailer": "https://www.youtube.com/watch?v=ZSdOwt-G49w",
      "imdb_id": "tt32890033",
      "tmdb_id": 1315772,
      "watchmode_url": "https://www.watchmode.com/title/1840434/",
      "poster_path": "/4LwvU9SZc8QQzW1X1FAPhNbXnEU.jpg",
      "backdrop_path": "/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/4LwvU9SZc8QQzW1X1FAPhNbXnEU.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg"
    },
    {
      "id": 1885279,
      "title": "The Super Mario Galaxy Movie",
      "year": 2026,
      "release_date": "2026-04-01",
      "genres": [
        "Family",
        "Comedy",
        "Adventure",
        "Fantasy",
        "Animation"
      ],
      "runtime_minutes": 98,
      "user_rating": 6.4,
      "critic_score": 40,
      "us_rating": "PG",
      "plot": "After stopping Bowser’s earlier scheme, two brothers face a new threat from his determined son, who wants to free his father and revive their family legacy. With familiar and new companions, the brothers journey across the stars to stop the young heir’s crusade.",
      "trailer": "https://www.youtube.com/watch?v=FdL2GorGdKc",
      "imdb_id": "tt28650488",
      "tmdb_id": 1226863,
      "watchmode_url": "https://www.watchmode.com/title/1885279/",
      "poster_path": "/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg",
      "backdrop_path": "/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg"
    }
  ]
};
