window.HYPE_MOVIES={
  "provider": "Watchmode",
  "image_provider": "TMDB",
  "generated_at": "2026-10-04T15:30:01.678Z",
  "refresh_hours": 24,
  "estimated_credits_this_refresh": 56,
  "tmdb_requests_this_refresh": 48,
  "popular": [
    {
      "id": 1939424,
      "title": "Resident Evil",
      "year": 2026,
      "release_date": "2026-09-16",
      "genres": [
        "Horror",
        "Science Fiction",
        "Adventure"
      ],
      "runtime_minutes": 95,
      "user_rating": 7.8,
      "critic_score": 88,
      "us_rating": null,
      "plot": "A medical courier finds himself fighting to survive when a horrifying night suddenly descends into chaos. Cut off from safety, he must navigate escalating danger and uncertainty while trying to make it through until morning.",
      "trailer": "https://www.youtube.com/watch?v=mNd1gb19A-c",
      "imdb_id": "tt35538033",
      "tmdb_id": 1423191,
      "watchmode_url": "https://www.watchmode.com/title/1939424/",
      "poster_path": "/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg",
      "backdrop_path": "/3icyRAqgakNcQn6aDVz9libFmBA.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/3icyRAqgakNcQn6aDVz9libFmBA.jpg"
    },
    {
      "id": 1869118,
      "title": "The Odyssey",
      "year": 2026,
      "release_date": "2026-07-15",
      "genres": [
        "Adventure",
        "Action",
        "Fantasy"
      ],
      "runtime_minutes": 173,
      "user_rating": 8.5,
      "critic_score": 91,
      "us_rating": "R",
      "plot": "After a devastating war, a legendary king begins a long, perilous journey home. Along the way, he faces powerful gods, terrifying monsters, dangerous temptations, and difficult choices that test his cleverness, courage, and humanity, while his family struggles with his prolonged absence and uncertainty about his return.",
      "trailer": "https://www.youtube.com/watch?v=Mzw2ttJD2qQ",
      "imdb_id": "tt33764258",
      "tmdb_id": 1368337,
      "watchmode_url": "https://www.watchmode.com/title/1869118/",
      "poster_path": "/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg",
      "backdrop_path": "/bulFtfy3oBQtCnAMSi7g6DSSds3.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/bulFtfy3oBQtCnAMSi7g6DSSds3.jpg"
    },
    {
      "id": 1773876,
      "title": "Spider-Man: Brand New Day",
      "year": 2026,
      "release_date": "2026-07-29",
      "genres": [
        "Science Fiction",
        "Action",
        "Adventure"
      ],
      "runtime_minutes": 145,
      "user_rating": 8.2,
      "critic_score": 78,
      "us_rating": "PG-13",
      "plot": "A full-time crimefighter protects a city that has forgotten who he is, while watching people from his past move on without him. As loneliness and strange changes in his abilities add to the pressure, he must face a dangerous new threat that puts the city and those he cares about at risk.",
      "trailer": "https://www.youtube.com/watch?v=62bIsvRcPv0",
      "imdb_id": "tt22084616",
      "tmdb_id": 969681,
      "watchmode_url": "https://www.watchmode.com/title/1773876/",
      "poster_path": "/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg",
      "backdrop_path": "/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg"
    },
    {
      "id": 191063,
      "title": "Loves of a French Pussycat",
      "year": 1972,
      "release_date": "1972-03-09",
      "genres": [
        "Comedy"
      ],
      "runtime_minutes": 94,
      "user_rating": 4.5,
      "critic_score": null,
      "us_rating": "R",
      "plot": "Rolf, a sex-advice columnist and a lecher, has affairs with numerous women, but never a permanent relationship. Suzanne, one of his ex-lovers, offers to bet that no woman can get Rolf to propose marriage, a bet her girlfriend Andrea eagerly accepts. But there's a catch: To win the bet, Andrea must get the womanizing Rolf to commit to marriage without first going to bed with him.",
      "trailer": null,
      "imdb_id": "tt0068986",
      "tmdb_id": 264980,
      "watchmode_url": "https://www.watchmode.com/title/191063/",
      "poster_path": "/1WGq9cMuj09tnTJ5wdkINOJff04.jpg",
      "backdrop_path": "/wVg11RahrRfghgqViuoJgcJL1iM.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/1WGq9cMuj09tnTJ5wdkINOJff04.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/wVg11RahrRfghgqViuoJgcJL1iM.jpg"
    },
    {
      "id": 11042837,
      "title": "The Love Hypothesis",
      "year": 2026,
      "release_date": "2026-09-23",
      "genres": [
        "Romance",
        "Comedy"
      ],
      "runtime_minutes": 112,
      "user_rating": 7.1,
      "critic_score": 68,
      "us_rating": "R",
      "plot": "A biology PhD candidate and a demanding professor enter a fake relationship to solve their romantic dilemmas. What begins as a carefully planned arrangement soon complicates their views on love, forcing both to navigate unexpected feelings and the pressures of academic life.",
      "trailer": "https://www.youtube.com/watch?v=xwdamnfS6IM",
      "imdb_id": "tt22526100",
      "tmdb_id": 1032863,
      "watchmode_url": "https://www.watchmode.com/title/11042837/",
      "poster_path": "/vfZxVHextAGC70zrNhS8lsROqP1.jpg",
      "backdrop_path": "/o7Oy9Gbx1CCyaweL8xUhtMW4Puq.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/vfZxVHextAGC70zrNhS8lsROqP1.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/o7Oy9Gbx1CCyaweL8xUhtMW4Puq.jpg"
    },
    {
      "id": 1624092,
      "title": "Coyote vs. Acme",
      "year": 2026,
      "release_date": "2026-08-17",
      "genres": [
        "Comedy",
        "Adventure",
        "Family"
      ],
      "runtime_minutes": 103,
      "user_rating": 7.6,
      "critic_score": 87,
      "us_rating": "PG",
      "plot": "After another Acme product backfires during his pursuit of the Roadrunner, a determined coyote takes the corporation to court with help from a struggling billboard lawyer. Their case brings cartoon chaos, courtroom clashes, and a fresh challenge for the company behind his long-running disasters.",
      "trailer": "https://www.youtube.com/watch?v=H-43VeYGiPM",
      "imdb_id": "tt1756855",
      "tmdb_id": 1204680,
      "watchmode_url": "https://www.watchmode.com/title/1624092/",
      "poster_path": "/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg",
      "backdrop_path": "/viZqGq9TNvQ5uXSD4ahg2RpRONT.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/viZqGq9TNvQ5uXSD4ahg2RpRONT.jpg"
    },
    {
      "id": 1882453,
      "title": "The End of Oak Street",
      "year": 2026,
      "release_date": "2026-08-12",
      "genres": [
        "Science Fiction",
        "Mystery",
        "Thriller"
      ],
      "runtime_minutes": 100,
      "user_rating": 6.4,
      "critic_score": 78,
      "us_rating": "PG-13",
      "plot": "After a mysterious cosmic event tears an ordinary suburban neighborhood from its surroundings, a family finds itself in an unknown, prehistoric wilderness. With familiar streets transformed and danger closing in, they must work together to survive, protect one another, and find a way forward.",
      "trailer": "https://www.youtube.com/watch?v=3oB9AxspVow",
      "imdb_id": "tt27165187",
      "tmdb_id": 1101383,
      "watchmode_url": "https://www.watchmode.com/title/1882453/",
      "poster_path": "/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg",
      "backdrop_path": "/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg"
    },
    {
      "id": 1875027,
      "title": "Runner",
      "year": 2026,
      "release_date": "2026-09-07",
      "genres": [
        "Action",
        "Comedy"
      ],
      "runtime_minutes": 97,
      "user_rating": 6.6,
      "critic_score": 66,
      "us_rating": "PG-13",
      "plot": "A former soldier and an unlikely partner race across dangerous territory to complete a critical medical delivery. Hunted by a ruthless cartel, they must stay ahead of their pursuers while trying to save a little girl’s life.",
      "trailer": "https://www.youtube.com/watch?v=m8JUmBgHejI",
      "imdb_id": "tt31349844",
      "tmdb_id": 1377237,
      "watchmode_url": "https://www.watchmode.com/title/1875027/",
      "poster_path": "/yBKMAIj7clP42UkFejhGDBBoTpb.jpg",
      "backdrop_path": "/2c9zNZJL0ZdagD6JbmU3hH4hovs.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/yBKMAIj7clP42UkFejhGDBBoTpb.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/2c9zNZJL0ZdagD6JbmU3hH4hovs.jpg"
    },
    {
      "id": 1873959,
      "title": "Colony",
      "year": 2026,
      "release_date": "2026-05-21",
      "genres": [
        "Horror",
        "Action",
        "Science Fiction"
      ],
      "runtime_minutes": 123,
      "user_rating": 6.7,
      "critic_score": 70,
      "us_rating": null,
      "plot": "During a biotech conference, a rapidly mutating virus is released, sealing a professor and a small group of survivors inside the facility. As infected people undergo horrifying changes and become increasingly dangerous, the trapped group must find a way to survive and confront the spreading threat.",
      "trailer": "https://www.youtube.com/watch?v=xQAXT17Jz18",
      "imdb_id": "tt34385135",
      "tmdb_id": 1375646,
      "watchmode_url": "https://www.watchmode.com/title/1873959/",
      "poster_path": "/tN799oUR0f1gUKDYdMNrDaY7I51.jpg",
      "backdrop_path": "/hpBGCnzOvdtQoMyE48gvwp2y5yx.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/tN799oUR0f1gUKDYdMNrDaY7I51.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/hpBGCnzOvdtQoMyE48gvwp2y5yx.jpg"
    },
    {
      "id": 1793884,
      "title": "Digger",
      "year": 2026,
      "release_date": "2026-09-28",
      "genres": [
        "Comedy",
        "Drama"
      ],
      "runtime_minutes": 129,
      "user_rating": 7.4,
      "critic_score": null,
      "us_rating": "R",
      "plot": "The most powerful man in the world embarks on a frantic mission to prove he is humanity's savior before the disaster he's unleashed destroys everything.",
      "trailer": "https://www.youtube.com/watch?v=Pd4Olzi0HEc",
      "imdb_id": "tt31450459",
      "tmdb_id": 1248832,
      "watchmode_url": "https://www.watchmode.com/title/1793884/",
      "poster_path": "/1ATXKrIPJyKNwnJ6lcG088Sa6zi.jpg",
      "backdrop_path": "/b7t3r39Oll5qPxBKzLZ8eHMBD7l.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/1ATXKrIPJyKNwnJ6lcG088Sa6zi.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/b7t3r39Oll5qPxBKzLZ8eHMBD7l.jpg"
    },
    {
      "id": 1779945,
      "title": "The Fix",
      "year": 2026,
      "release_date": "2026-09-10",
      "genres": [
        "Action",
        "Thriller"
      ],
      "runtime_minutes": 142,
      "user_rating": 4.9,
      "critic_score": null,
      "us_rating": "R",
      "plot": "Disillusioned by the end of the war in Afghanistan, a group of disgraced, war-torn former CIA operatives sets out for Tehran to pursue a life-changing score, confronting the consequences of their past while risking everything on an ambitious mission.",
      "trailer": "https://www.youtube.com/watch?v=NYC0v8xqQdM",
      "imdb_id": "tt9601292",
      "tmdb_id": 1228834,
      "watchmode_url": "https://www.watchmode.com/title/1779945/",
      "poster_path": "/yopXjun3ICFfJci2ukcEzceZjUs.jpg",
      "backdrop_path": "/yT8EkAvEkJDFeAxK7s7HlIPELRT.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/yopXjun3ICFfJci2ukcEzceZjUs.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/yT8EkAvEkJDFeAxK7s7HlIPELRT.jpg"
    },
    {
      "id": 11229413,
      "title": "After Impact",
      "year": 2026,
      "release_date": "2026-09-15",
      "genres": [
        "Science Fiction",
        "Drama",
        "Thriller"
      ],
      "runtime_minutes": 95,
      "user_rating": 3.2,
      "critic_score": null,
      "us_rating": "NR",
      "plot": "After losing a parent, a man inherits a vast greenhouse as an asteroid threatens Earth. As society breaks down, he retreats to a family bunker and struggles with injury, isolation, betrayal, and the difficult choices survival demands when a faint radio signal suggests someone else may still be out there.",
      "trailer": "https://www.youtube.com/watch?v=Af8D6sRDyxo",
      "imdb_id": "tt36809539",
      "tmdb_id": 1751701,
      "watchmode_url": "https://www.watchmode.com/title/11229413/",
      "poster_path": "/yzDuAQCY2n6zzOlBkn6JzhLhY3k.jpg",
      "backdrop_path": "/k22XyPbce7zvzzf5OnT4uaY8ZD1.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/yzDuAQCY2n6zzOlBkn6JzhLhY3k.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/k22XyPbce7zvzzf5OnT4uaY8ZD1.jpg"
    },
    {
      "id": 11001943,
      "title": "UNABOMBER",
      "year": 2026,
      "release_date": "2026-09-25",
      "genres": [
        "Thriller",
        "Drama",
        "Crime"
      ],
      "runtime_minutes": 101,
      "user_rating": 6.1,
      "critic_score": 37,
      "us_rating": "R",
      "plot": "A gifted young man’s life takes a troubling turn after he is subjected to controversial psychological experiments. Decades later, an FBI-led manhunt brings his past back into focus, tracing the consequences of ambition and isolation.",
      "trailer": "https://www.youtube.com/watch?v=B3tR6qQjbgI",
      "imdb_id": "tt6933238",
      "tmdb_id": 1492640,
      "watchmode_url": "https://www.watchmode.com/title/11001943/",
      "poster_path": "/39aMkR8Y5vhCG9dTkjiqRl8AVqp.jpg",
      "backdrop_path": "/58D9nalUYW5L5K0guw7hcpsEJBH.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/39aMkR8Y5vhCG9dTkjiqRl8AVqp.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/58D9nalUYW5L5K0guw7hcpsEJBH.jpg"
    },
    {
      "id": 1927112,
      "title": "Heart of the Beast",
      "year": 2026,
      "release_date": "2026-09-19",
      "genres": [
        "Adventure",
        "Thriller"
      ],
      "runtime_minutes": 101,
      "user_rating": 7.5,
      "critic_score": 76,
      "us_rating": "PG-13",
      "plot": "After a devastating plane crash, a Special Forces officer and his combat dog become stranded in the Alaskan wilderness. Facing harsh conditions and constant danger, the pair must rely on their bond, instincts, and survival skills to endure the unforgiving environment.",
      "trailer": "https://www.youtube.com/watch?v=JFQcDFhNh4o",
      "imdb_id": "tt7526136",
      "tmdb_id": 1263337,
      "watchmode_url": "https://www.watchmode.com/title/1927112/",
      "poster_path": "/1ApfSA8JTqeha3GTFEY8syV4auq.jpg",
      "backdrop_path": "/bicMU6xVD5deVyKP2azpyx7xkmH.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/1ApfSA8JTqeha3GTFEY8syV4auq.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/bicMU6xVD5deVyKP2azpyx7xkmH.jpg"
    },
    {
      "id": 1855581,
      "title": "Obsession",
      "year": 2026,
      "release_date": "2026-05-13",
      "genres": [
        "Horror",
        "Thriller"
      ],
      "runtime_minutes": 109,
      "user_rating": 8,
      "critic_score": 85,
      "us_rating": null,
      "plot": "After using a mysterious wish-granting object to win over his longtime crush, a hopeful romantic gets exactly what he wanted. But the altered relationship quickly turns unsettling, forcing him to confront the frightening consequences of trying to control another person’s feelings.",
      "trailer": "https://www.youtube.com/watch?v=0G5CjgPw1x4",
      "imdb_id": "tt37287335",
      "tmdb_id": 1339713,
      "watchmode_url": "https://www.watchmode.com/title/1855581/",
      "poster_path": "/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg",
      "backdrop_path": "/5lTZyuBTNOfawsfPT8Q0cIg6qAF.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/5lTZyuBTNOfawsfPT8Q0cIg6qAF.jpg"
    },
    {
      "id": 1823785,
      "title": "Toy Story 5",
      "year": 2026,
      "release_date": "2026-06-17",
      "genres": [
        "Animation",
        "Family",
        "Comedy",
        "Adventure"
      ],
      "runtime_minutes": 102,
      "user_rating": 7.5,
      "critic_score": 83,
      "us_rating": null,
      "plot": "When a child becomes absorbed in a new tablet, her beloved toys face an unexpected challenge to playtime. As the group struggles to stay connected with her, they must adapt to changing interests and work together to protect their place in her world.",
      "trailer": "https://www.youtube.com/watch?v=c51ND9Hdbw0",
      "imdb_id": "tt29355505",
      "tmdb_id": 1084244,
      "watchmode_url": "https://www.watchmode.com/title/1823785/",
      "poster_path": "/sfQtVlIHljToOwYjhe21KPGzZWK.jpg",
      "backdrop_path": "/qjTqY5coNiz6sVtPng40IzltsoN.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/sfQtVlIHljToOwYjhe21KPGzZWK.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/qjTqY5coNiz6sVtPng40IzltsoN.jpg"
    },
    {
      "id": 1513886,
      "title": "Resident Evil: Welcome to Raccoon City",
      "year": 2021,
      "release_date": "2021-11-24",
      "genres": [
        "Action",
        "Horror",
        "Science Fiction"
      ],
      "runtime_minutes": 107,
      "user_rating": 5.4,
      "critic_score": 37,
      "us_rating": "R",
      "plot": "In a declining Midwestern town once dominated by a pharmaceutical company, a hidden evil is unleashed beneath the surface. As residents change and danger spreads, a small group of survivors must work together to uncover the truth and survive the night.",
      "trailer": "https://www.youtube.com/watch?v=4q6UGCyHZCI",
      "imdb_id": "tt6920084",
      "tmdb_id": 460458,
      "watchmode_url": "https://www.watchmode.com/title/1513886/",
      "poster_path": "/bArhvjRHl535XMaSh9VjInF2mSZ.jpg",
      "backdrop_path": "/wYtEvBmpBRXPdwGgr1gcWiwJSI7.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/bArhvjRHl535XMaSh9VjInF2mSZ.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/wYtEvBmpBRXPdwGgr1gcWiwJSI7.jpg"
    },
    {
      "id": 1959567,
      "title": "Drawn Together",
      "year": 2026,
      "release_date": "2026-09-09",
      "genres": [
        "Romance",
        "Thriller"
      ],
      "runtime_minutes": 104,
      "user_rating": 5.6,
      "critic_score": 41,
      "us_rating": null,
      "plot": "After being kidnapped and released, a wealthy businessman's daughter is assigned a bodyguard by her concerned father. Their difficult relationship gradually shifts as attraction grows, while they navigate a dangerous world filled with uncertainty and hidden agendas.",
      "trailer": "https://www.youtube.com/watch?v=J_dWSteW_7Y",
      "imdb_id": "tt36073210",
      "tmdb_id": 1440098,
      "watchmode_url": "https://www.watchmode.com/title/1959567/",
      "poster_path": "/6rpvddXbaQPOi0fB2HKWbZ3uUSg.jpg",
      "backdrop_path": "/i65y7cMae36K0giN0GRaMjAHUru.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/6rpvddXbaQPOi0fB2HKWbZ3uUSg.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/i65y7cMae36K0giN0GRaMjAHUru.jpg"
    },
    {
      "id": 1821586,
      "title": "Mutiny",
      "year": 2026,
      "release_date": "2026-08-19",
      "genres": [
        "Action",
        "Thriller"
      ],
      "runtime_minutes": 96,
      "user_rating": 5.9,
      "critic_score": 51,
      "us_rating": "R",
      "plot": "After witnessing his employer’s murder and being framed for the crime, a disgraced former policeman hides aboard a cargo ship to pursue revenge. As he navigates the vessel and faces a heavily armed crew, he uncovers a wider international conspiracy tied to the killing.",
      "trailer": "https://www.youtube.com/watch?v=FKSdXH89jbo",
      "imdb_id": "tt32338669",
      "tmdb_id": 1288445,
      "watchmode_url": "https://www.watchmode.com/title/1821586/",
      "poster_path": "/pu2VxGlpGwffOx292w18b1tv96j.jpg",
      "backdrop_path": "/e2QAGrEmbpmZpMymDRkDisJkvg9.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/pu2VxGlpGwffOx292w18b1tv96j.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/e2QAGrEmbpmZpMymDRkDisJkvg9.jpg"
    },
    {
      "id": 1684684,
      "title": "The Uprising",
      "year": 2026,
      "release_date": "2026-09-10",
      "genres": [
        "History",
        "Drama"
      ],
      "runtime_minutes": 128,
      "user_rating": 7.2,
      "critic_score": 58,
      "us_rating": "R",
      "plot": "As war and plague ravage 14th-century England, a humble peasant sparks a rebellion and unites ordinary people against royal power. Their desperate struggle for justice and survival unfolds across a country strained by suffering, inequality, and conflict.",
      "trailer": "https://www.youtube.com/watch?v=ZVkrhHebz1Q",
      "imdb_id": "tt36983905",
      "tmdb_id": 977942,
      "watchmode_url": "https://www.watchmode.com/title/1684684/",
      "poster_path": "/7TUl15TOsIvndKlgMWTtLgtEzZP.jpg",
      "backdrop_path": "/y0reRTsewsPh0ePtgvDeLIsb5Wk.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/7TUl15TOsIvndKlgMWTtLgtEzZP.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/y0reRTsewsPh0ePtgvDeLIsb5Wk.jpg"
    }
  ],
  "upcoming": [
    {
      "id": 1929812,
      "title": "The Spiral",
      "year": 2026,
      "release_date": "2026-10-08",
      "genres": [
        "Drama",
        "Thriller"
      ],
      "runtime_minutes": 115,
      "user_rating": 6.7,
      "critic_score": null,
      "us_rating": null,
      "plot": "On a stormy night in Rome, Anna arrives at her daughter Alice’s apartment with a devastating confession: their entire family history is built on a lie. Twenty years earlier, after a horrific accident that nearly cost Alice her leg, Anna claims she made a pact with a mysterious Stranger to save her. But the miracle came at a price. What she believed was a single desperate bargain has in fact unleashed a spiraling chain reaction — a domino effect of increasingly dark events that have haunted their lives ever since. Now, the Stranger has come to collect. And Anna is convinced that only Alice can break the spiral and set things right. But at what cost?",
      "trailer": "https://www.youtube.com/watch?v=OiPKYpJlRGM",
      "imdb_id": "tt23411728",
      "tmdb_id": 1412795,
      "watchmode_url": "https://www.watchmode.com/title/1929812/",
      "poster_path": "/hkpxitZPz3cKQMl2g0MxzKQdtpP.jpg",
      "backdrop_path": "/jsnatGViKLWlW3iqr2wrZNWSrRB.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/hkpxitZPz3cKQMl2g0MxzKQdtpP.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/jsnatGViKLWlW3iqr2wrZNWSrRB.jpg"
    },
    {
      "id": 1991632,
      "title": "Big Girls Don't Cry",
      "year": 2026,
      "release_date": "2026-10-08",
      "genres": [
        "Drama"
      ],
      "runtime_minutes": 100,
      "user_rating": 6.6,
      "critic_score": null,
      "us_rating": null,
      "plot": "Over one transformative summer in rural New Zealand in 2006, a 14-year-old explores desire and identity as she turns to the internet. Trying to imitate the people she longs to be loved by, she slowly discovers what feels real to her.",
      "trailer": "https://www.youtube.com/watch?v=oAu4gc1VyA8",
      "imdb_id": "tt36867663",
      "tmdb_id": 1477963,
      "watchmode_url": "https://www.watchmode.com/title/1991632/",
      "poster_path": "/u7AAna0FE3d0yIzlLeBbxIcvtp0.jpg",
      "backdrop_path": "/5SXqcE79Jn210KsFgIyIy7t1Kdo.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/u7AAna0FE3d0yIzlLeBbxIcvtp0.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/5SXqcE79Jn210KsFgIyIy7t1Kdo.jpg"
    },
    {
      "id": 1788404,
      "title": "A Prayer for the Dying",
      "year": 2026,
      "release_date": "2026-10-09",
      "genres": [
        "Drama",
        "Thriller"
      ],
      "runtime_minutes": 95,
      "user_rating": 5.8,
      "critic_score": null,
      "us_rating": "NR",
      "plot": "In 1870, a small Wisconsin town of Scandinavian settlers struggles with the aftermath of the Civil War. When a dangerous new threat emerges, a man must choose between protecting his young family and defending the community that gave him a renewed sense of purpose.",
      "trailer": "https://www.youtube.com/watch?v=xbQjXVk9Sps",
      "imdb_id": "tt31183803",
      "tmdb_id": 1241046,
      "watchmode_url": "https://www.watchmode.com/title/1788404/",
      "poster_path": "/kYIhGPwr5ztkvnRcD4GzZGfuNhv.jpg",
      "backdrop_path": "/yMqBFMvAGPw5aM4azNN07kSjNM0.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/kYIhGPwr5ztkvnRcD4GzZGfuNhv.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/yMqBFMvAGPw5aM4azNN07kSjNM0.jpg"
    },
    {
      "id": 1821329,
      "title": "Tenzing",
      "year": 2026,
      "release_date": "2026-10-09",
      "genres": [
        "Drama",
        "History"
      ],
      "runtime_minutes": 126,
      "user_rating": 7.6,
      "critic_score": null,
      "us_rating": null,
      "plot": "A determined man embarks on a high-stakes quest—and defies seemingly impossible odds—to fulfill his dream of being the first to reach the summit of Mount Everest.",
      "trailer": "https://www.youtube.com/watch?v=KkYCY5YR12U",
      "imdb_id": "tt6262770",
      "tmdb_id": 1288069,
      "watchmode_url": "https://www.watchmode.com/title/1821329/",
      "poster_path": "/eI0QW02PYqhnmIvLRdn9vrfVVP7.jpg",
      "backdrop_path": "/9MdxBPjI58xkzA7RtKX9xRKvlZp.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/eI0QW02PYqhnmIvLRdn9vrfVVP7.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/9MdxBPjI58xkzA7RtKX9xRKvlZp.jpg"
    },
    {
      "id": 1892191,
      "title": "Musk",
      "year": 2026,
      "release_date": "2026-10-09",
      "genres": [
        "Documentary"
      ],
      "runtime_minutes": 235,
      "user_rating": 7,
      "critic_score": null,
      "us_rating": null,
      "plot": "An incisive look behind the legend of Elon Musk, the world’s most heralded \"inventor-entrepreneur\" who has enormous influence on the world in which we all live.",
      "trailer": "https://www.youtube.com/watch?v=eY_8SyndC10",
      "imdb_id": "tt27041231",
      "tmdb_id": 1096228,
      "watchmode_url": "https://www.watchmode.com/title/1892191/",
      "poster_path": "/fAyZqyN78VYb0usFgsmYjxZIFcN.jpg",
      "backdrop_path": "/rbF8b5NqcN5SprJmWz9CwGquMGa.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/fAyZqyN78VYb0usFgsmYjxZIFcN.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/rbF8b5NqcN5SprJmWz9CwGquMGa.jpg"
    },
    {
      "id": 1920228,
      "title": "Devour",
      "year": 2025,
      "release_date": "2026-10-09",
      "genres": [
        "Horror",
        "Thriller",
        "Action"
      ],
      "runtime_minutes": 113,
      "user_rating": 5.2,
      "critic_score": null,
      "us_rating": null,
      "plot": "Stranded after a disastrous gig, an all-girl heavy metal band finds a woman in danger in a town ruled by a warlock, and crawling with cannibals, vampires, and a deadly werewolf, forcing them to fight for survival.",
      "trailer": "https://www.youtube.com/watch?v=jfXzYeXd9Y4",
      "imdb_id": "tt14541160",
      "tmdb_id": 1406253,
      "watchmode_url": "https://www.watchmode.com/title/1920228/",
      "poster_path": "/duzeXiCKKU9bJUcObIf9zNMZIrC.jpg",
      "backdrop_path": "/mH4p9AFcadWTSUVkgVOODXkgays.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/duzeXiCKKU9bJUcObIf9zNMZIrC.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/mH4p9AFcadWTSUVkgVOODXkgays.jpg"
    },
    {
      "id": 11000067,
      "title": "Always Lisa",
      "year": 2026,
      "release_date": "2026-10-12",
      "genres": [
        "Documentary",
        "Music"
      ],
      "runtime_minutes": 98,
      "user_rating": 7.3,
      "critic_score": null,
      "us_rating": null,
      "plot": "Documentary following global superstar LISA during a transformative year away from BLACKPINK, the K-pop phenomenon that made her one of the world's most recognizable performers. Documenting a year of risk, reinvention, and self-discovery as LISA begins to define her next chapter.",
      "trailer": "https://www.youtube.com/watch?v=KAjC7EFzGKU",
      "imdb_id": "tt37108970",
      "tmdb_id": 1489932,
      "watchmode_url": "https://www.watchmode.com/title/11000067/",
      "poster_path": "/pOZnrUX1UMblLiqq9ZtZUde3cQV.jpg",
      "backdrop_path": "/wJwTuwy1ZajIA6ivGjoe0Ee08XN.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/pOZnrUX1UMblLiqq9ZtZUde3cQV.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/wJwTuwy1ZajIA6ivGjoe0Ee08XN.jpg"
    },
    {
      "id": 1689779,
      "title": "Minotaur",
      "year": 2026,
      "release_date": "2026-10-14",
      "genres": [
        "Crime",
        "Drama",
        "Thriller"
      ],
      "runtime_minutes": 135,
      "user_rating": 7.7,
      "critic_score": 85,
      "us_rating": null,
      "plot": "When Gleb, a successful company director, finds himself under siege from mounting corporate pressures, an increasingly unstable world, and the discovery of his wife's affair, the collapse of his carefully ordered life accelerates toward violence.",
      "trailer": "https://www.youtube.com/watch?v=hTHeFP0mcuk",
      "imdb_id": "tt37118301",
      "tmdb_id": 848700,
      "watchmode_url": "https://www.watchmode.com/title/1689779/",
      "poster_path": "/bM37B5CuMWrPyGPpNsKzTGict4Q.jpg",
      "backdrop_path": "/i5HacpkXOKQ85lfbnMO3jXvAnPy.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/bM37B5CuMWrPyGPpNsKzTGict4Q.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/i5HacpkXOKQ85lfbnMO3jXvAnPy.jpg"
    },
    {
      "id": 1950265,
      "title": "Iron Boy",
      "year": 2026,
      "release_date": "2026-10-14",
      "genres": [
        "Animation"
      ],
      "runtime_minutes": 90,
      "user_rating": 7.6,
      "critic_score": 79,
      "us_rating": null,
      "plot": "In rural France, Christophe (10) tries to live up to his rigid and distant father on the family farm. But the young boy starts to lean over and collapse without warning — on the tractor, at school, at dinner... A doctor finds the solution: Christophe must wear an iron corset to keep himself upright. Forced to reinvent his life away from the farm, Christophe discovers a new passion for music, meets a new friend, and follows her into his first mischief. But will any of this really fix what is out of balance?",
      "trailer": null,
      "imdb_id": "tt36639956",
      "tmdb_id": 947493,
      "watchmode_url": "https://www.watchmode.com/title/1950265/",
      "poster_path": "/aXNm7mgW22mxCSwSV7i7GHjy6Ga.jpg",
      "backdrop_path": "/3e0Lzs4vDSHjRULFw6vPI4jyHd6.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/aXNm7mgW22mxCSwSV7i7GHjy6Ga.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/3e0Lzs4vDSHjRULFw6vPI4jyHd6.jpg"
    },
    {
      "id": 1757035,
      "title": "Wicker",
      "year": 2026,
      "release_date": "2026-10-21",
      "genres": [
        "Romance",
        "Fantasy",
        "Comedy"
      ],
      "runtime_minutes": 105,
      "user_rating": 7.2,
      "critic_score": 75,
      "us_rating": null,
      "plot": "In a tight-knit fishing village, a social outcast asks a local craftsperson to create a husband from wicker. As she grows unexpectedly attached to the handmade companion, the relationship stirs gossip and jealousy, putting pressure on the community’s fragile sense of order.",
      "trailer": "https://www.youtube.com/watch?v=HP0BWBWn14I",
      "imdb_id": "tt29611136",
      "tmdb_id": 1195803,
      "watchmode_url": "https://www.watchmode.com/title/1757035/",
      "poster_path": "/eOYkNDalgt1v6UGjw3AoFR5qo9D.jpg",
      "backdrop_path": "/xVh1ypMoVkMf5IB7y3hnRplJ14c.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/eOYkNDalgt1v6UGjw3AoFR5qo9D.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/xVh1ypMoVkMf5IB7y3hnRplJ14c.jpg"
    },
    {
      "id": 1914859,
      "title": "Clayface",
      "year": 2026,
      "release_date": "2026-10-21",
      "genres": [
        "Horror",
        "Thriller",
        "Science Fiction"
      ],
      "runtime_minutes": 108,
      "user_rating": 7.9,
      "critic_score": null,
      "us_rating": "R",
      "plot": "Matt Hagen's meteoric rise from Gotham street kid to Hollywood leading man is tragically cut short when a local crime boss's actions leave him horribly disfigured. Abandoned by his team and with nothing left, Matt seeks out a cutting edge treatment that miraculously returns him to his former self… but also unexpectedly affects his grip on reality, spiraling him down a destructive path of all-consuming revenge.",
      "trailer": "https://www.youtube.com/watch?v=OGO4Mqvo3jI",
      "imdb_id": "tt34890576",
      "tmdb_id": 1400940,
      "watchmode_url": "https://www.watchmode.com/title/1914859/",
      "poster_path": "/5jCpQnWPikggmQZoDp1eAi6BI6w.jpg",
      "backdrop_path": "/1A7s8zG4PF6YoJrncrTO6N4r0Sx.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/5jCpQnWPikggmQZoDp1eAi6BI6w.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/1A7s8zG4PF6YoJrncrTO6N4r0Sx.jpg"
    },
    {
      "id": 1969393,
      "title": "Coward",
      "year": 2026,
      "release_date": "2026-10-21",
      "genres": [
        "Drama",
        "Romance",
        "War"
      ],
      "runtime_minutes": 120,
      "user_rating": 7.1,
      "critic_score": 73,
      "us_rating": null,
      "plot": "During the First World War, soldiers working behind the front line struggle to keep their spirits up. Inspired by war rhetoric, each person searches for a personal way to cope amid the pressures of conflict.",
      "trailer": "https://www.youtube.com/watch?v=vyRlBGfVlvQ",
      "imdb_id": "tt39328391",
      "tmdb_id": 1437981,
      "watchmode_url": "https://www.watchmode.com/title/1969393/",
      "poster_path": "/l05jDisMYVVpyAH3zgx1bUqPocZ.jpg",
      "backdrop_path": "/tW0ZxAcvLNZiSvHnBS2lpNOGB2S.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/l05jDisMYVVpyAH3zgx1bUqPocZ.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/tW0ZxAcvLNZiSvHnBS2lpNOGB2S.jpg"
    },
    {
      "id": 11126829,
      "title": "La Gradiva",
      "year": 2026,
      "release_date": "2026-10-21",
      "genres": [
        "Drama"
      ],
      "runtime_minutes": 145,
      "user_rating": 7.3,
      "critic_score": 95,
      "us_rating": null,
      "plot": "Amid the ancient ruins of Pompeii, a group of French teenagers on a class trip to Naples grapple with anxiety and exhilaration ahead of their high school graduation.",
      "trailer": "https://www.youtube.com/watch?v=5yY6V9MbEoE",
      "imdb_id": "tt36107185",
      "tmdb_id": 1154730,
      "watchmode_url": "https://www.watchmode.com/title/11126829/",
      "poster_path": "/y6AkOgTEPM9nTJUOeyvHqlf6Bgp.jpg",
      "backdrop_path": "/9BmIu8JMoSWSyqNsIW9ue9CthPZ.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/y6AkOgTEPM9nTJUOeyvHqlf6Bgp.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/9BmIu8JMoSWSyqNsIW9ue9CthPZ.jpg"
    },
    {
      "id": 1987809,
      "title": "The Diary of a Chambermaid",
      "year": 2026,
      "release_date": "2026-10-23",
      "genres": [
        "Drama",
        "Comedy"
      ],
      "runtime_minutes": 94,
      "user_rating": 6.7,
      "critic_score": 76,
      "us_rating": null,
      "plot": "Gianina, a young Romanian chambermaid, works for a bourgeois family in Bordeaux and spends her evenings rehearsing a maid’s story with an amateur theater group. She cares for her employer’s son while her own daughter grows up far away in Romania, and as Christmas nears, the hope of reunion grows stronger.",
      "trailer": null,
      "imdb_id": "tt38785098",
      "tmdb_id": 1472813,
      "watchmode_url": "https://www.watchmode.com/title/1987809/",
      "poster_path": "/vktQLUEEjg1KZhXfDINqxZNB29x.jpg",
      "backdrop_path": "/bYaiKiCmTOnd2EW0yuzA4vno8g.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/vktQLUEEjg1KZhXfDINqxZNB29x.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/bYaiKiCmTOnd2EW0yuzA4vno8g.jpg"
    },
    {
      "id": 1988409,
      "title": "The Only Living Pickpocket in New York",
      "year": 2026,
      "release_date": "2026-10-23",
      "genres": [
        "Crime",
        "Drama"
      ],
      "runtime_minutes": 88,
      "user_rating": 7,
      "critic_score": null,
      "us_rating": null,
      "plot": "An aging pickpocket navigates a New York where cash is fading and his skills are tested. After he takes a valuable USB stick by mistake, he must race to return it and calm a dangerous crime family—while also caring for his disabled wife.",
      "trailer": "https://www.youtube.com/watch?v=iXA7BmrBBxs",
      "imdb_id": "tt36482679",
      "tmdb_id": 1458099,
      "watchmode_url": "https://www.watchmode.com/title/1988409/",
      "poster_path": "/pNdB9va2AEPQe9UfhKAdIt8nus9.jpg",
      "backdrop_path": "/nZLt2sLZTEOyK50TjwNlGqzWsp5.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/pNdB9va2AEPQe9UfhKAdIt8nus9.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/nZLt2sLZTEOyK50TjwNlGqzWsp5.jpg"
    },
    {
      "id": 11097329,
      "title": "BTS: THE RETURN",
      "year": 2026,
      "release_date": "2026-10-25",
      "genres": [
        "Documentary",
        "Music"
      ],
      "runtime_minutes": 93,
      "user_rating": 9.3,
      "critic_score": null,
      "us_rating": null,
      "plot": "A globally celebrated music group reunites in Los Angeles to record a new album. This documentary offers rare access to their creative process, group dynamic, and fresh chapter as they work together in a new era.",
      "trailer": "https://www.youtube.com/watch?v=jRig7JvOpWg",
      "imdb_id": "tt39578551",
      "tmdb_id": 1628116,
      "watchmode_url": "https://www.watchmode.com/title/11097329/",
      "poster_path": "/9CNUWleZWN9EGMZjvaSTcxmAAGg.jpg",
      "backdrop_path": "/w4jOh7ok6JvsYu6WbuSDW97D7D6.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/9CNUWleZWN9EGMZjvaSTcxmAAGg.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/w4jOh7ok6JvsYu6WbuSDW97D7D6.jpg"
    },
    {
      "id": 1953127,
      "title": "Moulin",
      "year": 2026,
      "release_date": "2026-10-28",
      "genres": [
        "History",
        "Drama",
        "War"
      ],
      "runtime_minutes": 130,
      "user_rating": 5.9,
      "critic_score": null,
      "us_rating": null,
      "plot": "In June 1943, Jean Moulin, leader of the French Resistance, is arrested while attempting to reunite the forces of the \"Armée Secrète.\" Interrogated by Klaus Barbie, the head of the Gestapo in Lyon, Moulin is drawn into a relentless confrontation.",
      "trailer": null,
      "imdb_id": "tt36899180",
      "tmdb_id": 1437925,
      "watchmode_url": "https://www.watchmode.com/title/1953127/",
      "poster_path": "/f3yopLJXRBcPvgkfRji1jloDrxd.jpg",
      "backdrop_path": "/bcH6CmYcHuPnAQXUhW0Rr5hFuvc.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/f3yopLJXRBcPvgkfRji1jloDrxd.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/bcH6CmYcHuPnAQXUhW0Rr5hFuvc.jpg"
    },
    {
      "id": 1985219,
      "title": "Sanguine",
      "year": 2026,
      "release_date": "2026-10-28",
      "genres": [
        "Science Fiction",
        "Horror"
      ],
      "runtime_minutes": 103,
      "user_rating": 6.4,
      "critic_score": null,
      "us_rating": null,
      "plot": "Margot, a young intern at the country's most competitive ER, struggles in the high-pressure environment. When multiple patients her age arrive with strange symptoms, her own body begins experiencing alarming transformations.",
      "trailer": "https://www.youtube.com/watch?v=56TE9NuZQhs",
      "imdb_id": "tt37799273",
      "tmdb_id": 1468846,
      "watchmode_url": "https://www.watchmode.com/title/1985219/",
      "poster_path": "/fDvZvNmLIwUcKKQ4Cfb6TmQJM7M.jpg",
      "backdrop_path": "/sIleLElPQo13FuWHzKmIeXq8msd.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/fDvZvNmLIwUcKKQ4Cfb6TmQJM7M.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/sIleLElPQo13FuWHzKmIeXq8msd.jpg"
    },
    {
      "id": 11021641,
      "title": "Ozzy & Black Sabbath: Back to the Beginning",
      "year": 2026,
      "release_date": "2026-10-28",
      "genres": [
        "Music",
        "Documentary"
      ],
      "runtime_minutes": 147,
      "user_rating": 8.6,
      "critic_score": null,
      "us_rating": null,
      "plot": "A landmark farewell concert reunites pioneering heavy metal performers for a high-energy celebration of classic songs. The live event also features guest artists and other bands performing tributes and original material, creating a powerful salute to the genre’s enduring legacy.",
      "trailer": null,
      "imdb_id": "tt46055956",
      "tmdb_id": 1515139,
      "watchmode_url": "https://www.watchmode.com/title/11021641/",
      "poster_path": "/iO8vwdtmOivoyUguheJtDLXp2Gq.jpg",
      "backdrop_path": "/hFIhPUW8oO2EJYXLAuWFMJBzjsR.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/iO8vwdtmOivoyUguheJtDLXp2Gq.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/hFIhPUW8oO2EJYXLAuWFMJBzjsR.jpg"
    },
    {
      "id": 1795869,
      "title": "The Blood Countess",
      "year": 2026,
      "release_date": "2026-10-29",
      "genres": [
        "Horror",
        "Comedy",
        "Fantasy",
        "Mystery"
      ],
      "runtime_minutes": 119,
      "user_rating": 5.1,
      "critic_score": null,
      "us_rating": null,
      "plot": "A powerful vampire and her maid pursue a legendary elixir and a book that could endanger their supernatural world. Chasing them are a determined police inspector, two vampire experts, an unconventional nephew, and his therapist.",
      "trailer": "https://www.youtube.com/watch?v=mpSqlS7stC0",
      "imdb_id": "tt28151657",
      "tmdb_id": 1251608,
      "watchmode_url": "https://www.watchmode.com/title/1795869/",
      "poster_path": "/jKIAwCSDTv9i4J6KrAY1YpEvrGH.jpg",
      "backdrop_path": "/9IdxfMvkZzO8wjnygz784OzaK03.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/jKIAwCSDTv9i4J6KrAY1YpEvrGH.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/9IdxfMvkZzO8wjnygz784OzaK03.jpg"
    }
  ],
  "kids": [
    {
      "id": 1749638,
      "title": "The Wild Robot",
      "year": 2024,
      "release_date": "2024-09-12",
      "genres": [
        "Family",
        "Animation",
        "Science Fiction",
        "Adventure"
      ],
      "runtime_minutes": 102,
      "user_rating": 8.3,
      "critic_score": 91,
      "us_rating": null,
      "plot": "After a shipwreck, an intelligent robot is stranded on an uninhabited island. As the robot learns to survive among wary animals, it forms an unexpected bond with an orphaned gosling and takes on the challenge of raising it in the wild.",
      "trailer": "https://www.youtube.com/watch?v=67vbA5ZJdKQ",
      "imdb_id": "tt29623480",
      "tmdb_id": 1184918,
      "watchmode_url": "https://www.watchmode.com/title/1749638/",
      "poster_path": "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
      "backdrop_path": "/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg"
    },
    {
      "id": 1184041,
      "title": "Inside Out",
      "year": 2015,
      "release_date": "2015-06-17",
      "genres": [
        "Animation",
        "Family",
        "Adventure",
        "Drama",
        "Comedy"
      ],
      "runtime_minutes": 95,
      "user_rating": 8.2,
      "critic_score": 96,
      "us_rating": "PG",
      "plot": "When an 11-year-old girl moves to a new city, her emotions struggle to guide her through the upheaval. As Joy and Sadness become separated from the others, they travel through unfamiliar parts of her mind while trying to restore balance and help her cope with change.",
      "trailer": "https://www.youtube.com/watch?v=_MC3XuMvsDI",
      "imdb_id": "tt2096673",
      "tmdb_id": 150540,
      "watchmode_url": "https://www.watchmode.com/title/1184041/",
      "poster_path": "/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
      "backdrop_path": "/jJKZaTBNenlFclQyjrnvzkRmvWE.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/jJKZaTBNenlFclQyjrnvzkRmvWE.jpg"
    },
    {
      "id": 1438467,
      "title": "Toy Story 2",
      "year": 1999,
      "release_date": "1999-10-30",
      "genres": [
        "Animation",
        "Comedy",
        "Family"
      ],
      "runtime_minutes": 92,
      "user_rating": 8,
      "critic_score": 94,
      "us_rating": "G",
      "plot": "When a beloved cowboy toy is taken by a collector, his friends set out on a daring rescue through shops, streets, and airport chaos. Along the way, he meets new companions and must consider whether his future belongs with a child or as part of a collection.",
      "trailer": "https://www.youtube.com/watch?v=Y7HW__Z24rQ",
      "imdb_id": "tt0120363",
      "tmdb_id": 863,
      "watchmode_url": "https://www.watchmode.com/title/1438467/",
      "poster_path": "/4rbcp3ng8n1MKHjpeqW0L7Fnpzz.jpg",
      "backdrop_path": "/nsfVr4QbbunUrHINN9N7JdVAMTf.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/4rbcp3ng8n1MKHjpeqW0L7Fnpzz.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/nsfVr4QbbunUrHINN9N7JdVAMTf.jpg"
    },
    {
      "id": 199607,
      "title": "Despicable Me",
      "year": 2010,
      "release_date": "2010-07-08",
      "genres": [
        "Animation",
        "Comedy",
        "Crime",
        "Science Fiction",
        "Family"
      ],
      "runtime_minutes": 95,
      "user_rating": 7.7,
      "critic_score": 76,
      "us_rating": "PG",
      "plot": "A determined supervillain devises an audacious plan to steal the Moon, but needs three orphaned girls to help him reach a rival's heavily protected gadget. As the scheme unfolds, the girls bring unexpected warmth and challenge his commitment to the criminal life.",
      "trailer": "https://www.youtube.com/watch?v=DsiayV5LuD0",
      "imdb_id": "tt1323594",
      "tmdb_id": 20352,
      "watchmode_url": "https://www.watchmode.com/title/199607/",
      "poster_path": "/b1BT309QWjtFUlJPLmXmrcHOWEL.jpg",
      "backdrop_path": "/2XSeKDmIa2KxaiJy4J9e8FrIZhk.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/b1BT309QWjtFUlJPLmXmrcHOWEL.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/2XSeKDmIa2KxaiJy4J9e8FrIZhk.jpg"
    },
    {
      "id": 1624092,
      "title": "Coyote vs. Acme",
      "year": 2026,
      "release_date": "2026-08-17",
      "genres": [
        "Comedy",
        "Adventure",
        "Family"
      ],
      "runtime_minutes": 103,
      "user_rating": 7.6,
      "critic_score": 87,
      "us_rating": "PG",
      "plot": "After another Acme product backfires during his pursuit of the Roadrunner, a determined coyote takes the corporation to court with help from a struggling billboard lawyer. Their case brings cartoon chaos, courtroom clashes, and a fresh challenge for the company behind his long-running disasters.",
      "trailer": "https://www.youtube.com/watch?v=H-43VeYGiPM",
      "imdb_id": "tt1756855",
      "tmdb_id": 1204680,
      "watchmode_url": "https://www.watchmode.com/title/1624092/",
      "poster_path": "/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg",
      "backdrop_path": "/viZqGq9TNvQ5uXSD4ahg2RpRONT.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/viZqGq9TNvQ5uXSD4ahg2RpRONT.jpg"
    },
    {
      "id": 1823785,
      "title": "Toy Story 5",
      "year": 2026,
      "release_date": "2026-06-17",
      "genres": [
        "Animation",
        "Family",
        "Comedy",
        "Adventure"
      ],
      "runtime_minutes": 102,
      "user_rating": 7.5,
      "critic_score": 83,
      "us_rating": null,
      "plot": "When a child becomes absorbed in a new tablet, her beloved toys face an unexpected challenge to playtime. As the group struggles to stay connected with her, they must adapt to changing interests and work together to protect their place in her world.",
      "trailer": "https://www.youtube.com/watch?v=c51ND9Hdbw0",
      "imdb_id": "tt29355505",
      "tmdb_id": 1084244,
      "watchmode_url": "https://www.watchmode.com/title/1823785/",
      "poster_path": "/sfQtVlIHljToOwYjhe21KPGzZWK.jpg",
      "backdrop_path": "/qjTqY5coNiz6sVtPng40IzltsoN.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/sfQtVlIHljToOwYjhe21KPGzZWK.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/qjTqY5coNiz6sVtPng40IzltsoN.jpg"
    },
    {
      "id": 1785478,
      "title": "Zootopia 2",
      "year": 2025,
      "release_date": "2025-11-26",
      "genres": [
        "Animation",
        "Adventure",
        "Comedy",
        "Mystery",
        "Family"
      ],
      "runtime_minutes": 108,
      "user_rating": 7.5,
      "critic_score": 83,
      "us_rating": "PG",
      "plot": "After solving a major case, two police partners follow a twisting mystery when a snake’s arrival disrupts the animal metropolis. Their investigation takes them undercover into unfamiliar parts of town, testing their teamwork while raising questions about prejudice, stereotypes, greed, and the city’s past.",
      "trailer": "https://www.youtube.com/watch?v=BjkIOU5PhyQ",
      "imdb_id": "tt26443597",
      "tmdb_id": 1084242,
      "watchmode_url": "https://www.watchmode.com/title/1785478/",
      "poster_path": "/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg",
      "backdrop_path": "/lgotja3xMoJZbynwHfcQcJAEMWH.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/lgotja3xMoJZbynwHfcQcJAEMWH.jpg"
    },
    {
      "id": 1840434,
      "title": "Minions & Monsters",
      "year": 2026,
      "release_date": "2026-06-24",
      "genres": [
        "Adventure",
        "Animation",
        "Comedy",
        "Family",
        "Fantasy"
      ],
      "runtime_minutes": 90,
      "user_rating": 6.5,
      "critic_score": 80,
      "us_rating": "PG",
      "plot": "A group of chaotic yellow movie hopefuls storms Hollywood and becomes famous before a major change sends them tumbling back down. When their attempt to make a monster movie unleashes real danger, they must work together to stop the mayhem and protect the world.",
      "trailer": "https://www.youtube.com/watch?v=ZSdOwt-G49w",
      "imdb_id": "tt32890033",
      "tmdb_id": 1315772,
      "watchmode_url": "https://www.watchmode.com/title/1840434/",
      "poster_path": "/4LwvU9SZc8QQzW1X1FAPhNbXnEU.jpg",
      "backdrop_path": "/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/4LwvU9SZc8QQzW1X1FAPhNbXnEU.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg"
    },
    {
      "id": 1885279,
      "title": "The Super Mario Galaxy Movie",
      "year": 2026,
      "release_date": "2026-04-01",
      "genres": [
        "Family",
        "Comedy",
        "Adventure",
        "Fantasy",
        "Animation"
      ],
      "runtime_minutes": 98,
      "user_rating": 6.4,
      "critic_score": 40,
      "us_rating": "PG",
      "plot": "After stopping Bowser’s earlier scheme, two brothers face a new threat from his determined son, who wants to free his father and revive their family legacy. With familiar and new companions, the brothers journey across the stars to stop the young heir’s crusade.",
      "trailer": "https://www.youtube.com/watch?v=FdL2GorGdKc",
      "imdb_id": "tt28650488",
      "tmdb_id": 1226863,
      "watchmode_url": "https://www.watchmode.com/title/1885279/",
      "poster_path": "/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg",
      "backdrop_path": "/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg"
    },
    {
      "id": 1894118,
      "title": "PAW Patrol: The Dino Movie",
      "year": 2026,
      "release_date": "2026-07-23",
      "genres": [
        "Animation",
        "Adventure",
        "Family",
        "Fantasy",
        "Comedy"
      ],
      "runtime_minutes": 88,
      "user_rating": 6.3,
      "critic_score": 52,
      "us_rating": "PG",
      "plot": "A team of brave rescue pups lands on a mysterious dinosaur island after a storm, where they meet a stranded pup. When reckless mining activity awakens a volcano, the team must mount its biggest rescue mission yet to protect the island and its inhabitants.",
      "trailer": "https://www.youtube.com/watch?v=xgI5iYmOf5Q",
      "imdb_id": "tt29356163",
      "tmdb_id": 1185806,
      "watchmode_url": "https://www.watchmode.com/title/1894118/",
      "poster_path": "/qnin56Syy5rbG7KCaxWY7SPuy6p.jpg",
      "backdrop_path": "/c9Vatzm113Q3HgYsqThfYf0mpsr.jpg",
      "poster_url": "https://image.tmdb.org/t/p/w500/qnin56Syy5rbG7KCaxWY7SPuy6p.jpg",
      "backdrop_url": "https://image.tmdb.org/t/p/w780/c9Vatzm113Q3HgYsqThfYf0mpsr.jpg"
    }
  ]
};
